name: mobile_pos
description: THQ ERP Mobile POS
publish_to: 'none'
version: 6.0.0+1
environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  thq_ui:
    path: ../../packages/thq_ui
  cupertino_icons: 1.0.8
  supabase_flutter: 2.17.2
  flutter_secure_storage: 10.3.1
  uuid: 4.6.0
  intl: 0.20.3
  path: 1.9.1
  path_provider: 2.1.6
  sqflite: 2.4.3
  pdf: 3.13.0
  printing: 5.15.0
  mobile_scanner: 7.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
flutter:
  uses-material-design: true
