do $test$
declare
 t uuid:=gen_random_uuid();usr uuid:=gen_random_uuid();membership uuid:=gen_random_uuid();owner_role uuid;
 loc uuid:=gen_random_uuid();device uuid:=gen_random_uuid();customer uuid:=gen_random_uuid();prod uuid:=gen_random_uuid();variant uuid:=gen_random_uuid();unit uuid:=gen_random_uuid();reg uuid:=gen_random_uuid();profile uuid:=gen_random_uuid();
 items jsonb;q jsonb;r jsonb;again jsonb;sale uuid;request text;checks jsonb:='{}';bad boolean;load_id uuid:=gen_random_uuid();stranger uuid:=gen_random_uuid();
begin
 begin
  insert into public.tenants(id,name,slug,business_type) values(t,'Invoice rollback store','invoice-rollback-'||t,'material_yard');
  insert into auth.users(id,aud,role,email) values(usr,'authenticated','authenticated','invoice-rollback-'||usr||'@example.invalid');
  insert into public.tenant_memberships(id,tenant_id,user_id) values(membership,t,usr);
  select id into owner_role from public.roles where tenant_id=t and key='owner' limit 1;
  if owner_role is null then insert into public.roles(tenant_id,key,name) values(t,'owner','Owner') returning id into owner_role;end if;
  insert into public.role_permissions(role_id,permission_key) select owner_role,key from public.permissions on conflict do nothing;
  insert into public.user_roles(tenant_id,membership_id,role_id) values(t,membership,owner_role);
  perform set_config('request.jwt.claim.sub',usr::text,true);
  perform private.v47_ensure_accounting_for_tenant(t);
  perform private.v628_seed_payment_methods(t);
  insert into public.business_locations(id,tenant_id,location_code,name,invoice_prefix,state,address_line1) values(loc,t,'ROLLBACK-'||loc,'Invoice rollback location','TST','Maharashtra','Test address');
  insert into public.business_devices(id,tenant_id,location_id,device_code,name,app_type,status,invoice_prefix) values(device,t,loc,'ROLLBACK-'||device,'Invoice rollback client','client','active','TST');
  insert into public.customers(id,tenant_id,name,state,is_walk_in) values(customer,t,'Invoice rollback customer','Maharashtra',false);
  insert into public.inventory_units_v481(id,tenant_id,code,name) values(unit,t,'TESTUNIT','Test unit');
  insert into public.products(id,tenant_id,name,item_type,base_unit_id,tax_rate) values(prod,t,'Rollback service','service',unit,18);
  insert into public.product_variants(id,tenant_id,product_id,name,sku,selling_price) values(variant,t,prod,'Default','ROLLBACK-'||variant,100);
  insert into public.product_units_v481(tenant_id,variant_id,unit_id,is_base,is_default_sale,allow_sale) values(t,variant,unit,true,true,true);
  if private.gst_tax_mode_resolve_v520(t,current_date)<>'non_gst' then raise exception 'Fresh unregistered store did not default to normal billing';end if;
  q:=public.sales_invoice_context_v632(t,loc,device,current_date,null);
  if q->>'tax_mode'<>'non_gst' or (q->>'gst_applicable')::boolean then raise exception 'Incorrect non-GST form context';end if;
  bad:=false;begin perform public.sales_invoice_context_v632(gen_random_uuid(),loc,device,current_date,null);exception when sqlstate '42501' then bad:=true;end;
  if not bad then raise exception 'Another tenant accessed invoice context';end if;
  perform set_config('request.jwt.claim.sub','',true);
  bad:=false;begin perform public.sales_invoice_context_v632(t,loc,device,current_date,null);exception when sqlstate '42501' then bad:=true;end;
  if not bad then raise exception 'Unauthenticated invoice context accepted';end if;
  perform set_config('request.jwt.claim.sub',usr::text,true);
  if has_function_privilege('anon','public.sales_invoice_context_v632(uuid,uuid,uuid,date,uuid)','execute')
     or has_function_privilege('authenticated','private.sale_items_for_tax_mode_v632(uuid,date,jsonb)','execute')
     or has_function_privilege('authenticated','private.invoice_calculate_allowed_v632(uuid,date,text)','execute') then raise exception 'Invoice helper privileges exposed';end if;
  checks:=checks||jsonb_build_object('tenant_and_anonymous_access_blocked','PASS','helper_acl','PASS');
  items:=jsonb_build_array(jsonb_build_object('variant_id',variant,'unit_id',unit,'quantity',1,'unit_price',100,'discount_amount',0,'tax_rate',18,'thq_manual_price_v630',true,'thq_tax_override_v630',jsonb_build_object('gst_rate',5)));
  update public.roles set key='rollback_clerk' where id=owner_role;
  delete from public.role_permissions where role_id=owner_role and permission_key like 'gst_compliance.%';
  insert into public.business_user_app_access(tenant_id,user_id,app_key,enabled) values(t,usr,'client',true);
  insert into public.business_user_location_access(tenant_id,user_id,location_id,access_level) values(t,usr,loc,'operate');
  if private.gst_v520_has_access(t,'gst_compliance.calculate') then raise exception 'Fixture still has GST calculation permission';end if;
  perform public.gst_transaction_cutover_contract_v522(t,'client',device);
  q:=public.client_sale_quote_v630(t,customer,current_date,items,loc,device,null,null,'[]',null);
  if (q->'totals'->>'tax')::numeric<>0 or (q->'totals'->>'grand_total')::numeric<>100 then raise exception 'Non-GST stale tax quote failed: %',q;end if;
  request:=gen_random_uuid()::text;
  r:=public.gst_client_sale_create_v630(t,customer,current_date,current_date,items,'[{"method_code":"cash","amount":100}]','Rollback unregistered invoice',loc,device,request,null,null,'[]');sale:=(r->>'sale_id')::uuid;
  again:=public.gst_client_sale_create_v630(t,customer,current_date,current_date,items,'[{"method_code":"cash","amount":100}]','Rollback unregistered invoice',loc,device,request,null,null,'[]');
  if (again->>'sale_id')::uuid<>sale or (r->>'tax_total')::numeric<>0 then raise exception 'Non-GST retry/zero-tax writer failed';end if;
  q:=public.sales_get_detail_v630(t,sale);
  if q->'gst'->>'tax_mode'<>'non_gst' or q->'gst'->>'document_class'<>'commercial_invoice' or (q->'gst'->>'tax_collected_total')::numeric<>0 then raise exception 'Saved non-GST invoice lost its mode: %',q->'gst';end if;
  if exists(select 1 from public.journal_lines where journal_entry_id=(r->>'journal_id')::uuid group by journal_entry_id having abs(sum(debit-credit))>.005) then raise exception 'Unregistered journal imbalance';end if;
  checks:=checks||jsonb_build_object('unconfigured_unregistered_billing','PASS','no_gst_module_permissions_needed','PASS','stale_tax_ignored','PASS','zero_tax_saved_invoice','PASS','idempotent_retry','PASS','non_gst_journal','PASS');

  insert into public.tenant_modules(tenant_id,module_key,enabled) values(t,'aggregate_yard',true) on conflict(tenant_id,module_key) do update set enabled=true;
  insert into public.customers(id,tenant_id,name,state) values(stranger,t,'Different customer','Maharashtra');
  insert into public.aggregate_loads_v617(id,tenant_id,load_number,direction,status,location_id,variant_id,product_name_snapshot,quantity,customer_id) values(load_id,t,'ROLLBACK-'||load_id,'outbound','completed',loc,variant,'Rollback load',1,customer);
  q:=public.sales_invoice_context_v632(t,loc,device,current_date,load_id);
  if q->>'locked_customer_id'<>customer::text then raise exception 'Confirmed load customer not returned';end if;
  bad:=false;begin perform public.client_sale_quote_v630(t,stranger,current_date,items,loc,device,null,null,'[]',load_id);exception when others then if sqlerrm not like '%customer recorded on the confirmed Load Ticket%' then raise;end if;bad:=true;end;
  if not bad then raise exception 'Wrong customer quote accepted';end if;
  bad:=false;begin perform public.aggregate_load_sale_create_v630(t,load_id,stranger,current_date,current_date,items,'[{"method_code":"cash","amount":100}]','Wrong load customer',loc,device,gen_random_uuid()::text,null,null,'[]');exception when others then if sqlerrm not like '%customer recorded on the confirmed Load Ticket%' then raise;end if;bad:=true;end;
  if not bad then raise exception 'Wrong customer load invoice accepted';end if;
  checks:=checks||jsonb_build_object('load_customer_context_and_quote_guard','PASS','load_customer_writer_guard','PASS');
  update public.roles set key='owner' where id=owner_role;
  insert into public.role_permissions(role_id,permission_key) select owner_role,key from public.permissions on conflict do nothing;
  insert into public.gst_tenant_tax_modes_v520(tenant_id,tax_mode,effective_from,reason) values(t,'gst_registered',current_date,'Rollback fixture');
  perform private.gst_v520_ensure_accounts(t);
  q:=public.gst_quote_v520(t,loc,'customer',customer,current_date,'B2C','27',items,0,0);
  if (q->>'ready_for_compliance')::boolean then raise exception 'Registered but incomplete GST setup was accepted';end if;
  insert into public.gst_registrations_v520(id,tenant_id,gstin,legal_name,state_code,address_line1) values(reg,t,'27AAPFU0939F1ZV','Rollback registered business','27','Test address');
  insert into public.gst_registration_versions_v520(tenant_id,registration_id,legal_name,registration_type,address_line1,effective_from) values(t,reg,'Rollback registered business','regular','Test address',current_date);
  insert into public.gst_location_registrations_v520(tenant_id,location_id,registration_id,effective_from) values(t,loc,reg,current_date);
  insert into public.gst_product_tax_profiles_v520(id,tenant_id,variant_id,supply_kind,hsn_sac,gst_rate,validation_status,effective_from) values(profile,t,variant,'service','998313',18,'locally_validated',current_date);
  items:=jsonb_set(items,'{0}',(items->0)-'thq_tax_override_v630');
  q:=public.client_sale_quote_v630(t,customer,current_date,items,loc,device,'B2C','27','[]',null);
  if (q->'totals'->>'tax')::numeric<>18 or (q->'totals'->>'grand_total')::numeric<>118 then raise exception 'Registered local components failed: %',q;end if;
  q:=public.client_sale_quote_v630(t,customer,current_date,items,loc,device,'B2C','32','[]',null);
  if (q->'gst'->'totals'->>'igst')::numeric<>18 or (q->'gst'->'totals'->>'cgst')::numeric<>0 then raise exception 'Registered interstate components failed';end if;
  update public.gst_product_tax_profiles_v520 set validation_status='review_required' where id=profile;
  bad:=false;begin perform public.gst_client_sale_create_v630(t,customer,current_date,current_date,items,'[{"method_code":"cash","amount":118}]','Blocked profile',loc,device,gen_random_uuid()::text,'B2C','27','[]');exception when others then if sqlerrm not like '%review%' then raise;end if;bad:=true;end;
  if not bad then raise exception 'Unreviewed GST profile posted';end if;
  update public.gst_product_tax_profiles_v520 set validation_status='locally_validated' where id=profile;
  update public.gst_registrations_v520 set active=false where id=reg;
  q:=public.gst_quote_v520(t,loc,'customer',customer,current_date,'B2C','27',items,0,0);
  if (q->>'ready_for_compliance')::boolean then raise exception 'Inactive seller registration accepted';end if;
  update public.gst_registrations_v520 set active=true where id=reg;
  update public.gst_registration_versions_v520 set validation_status='review_required' where registration_id=reg;
  q:=public.gst_quote_v520(t,loc,'customer',customer,current_date,'B2C','27',items,0,0);
  if (q->>'ready_for_compliance')::boolean then raise exception 'Unreviewed seller configuration accepted';end if;
  update public.gst_registration_versions_v520 set validation_status='local_validated' where registration_id=reg;
  update public.gst_product_tax_profiles_v520 set hsn_sac='1234' where id=profile;
  q:=public.gst_quote_v520(t,loc,'customer',customer,current_date,'B2C','27',items,0,0);
  if (q->>'ready_for_compliance')::boolean then raise exception 'Invalid HSN/SAC accepted';end if;
  update public.gst_product_tax_profiles_v520 set hsn_sac='998313' where id=profile;
  q:=public.gst_quote_v520(t,loc,'customer',customer,current_date,'B2B','27',items,0,0);
  if (q->>'ready_for_compliance')::boolean then raise exception 'B2B without registered recipient accepted';end if;
  update public.gst_registration_versions_v520 set registration_type='composition' where registration_id=reg;
  q:=public.gst_quote_v520(t,loc,'customer',customer,current_date,'B2C','27',items,0,0);
  if q->>'document_class'<>'bill_of_supply' or (q->'totals'->>'tax_collected_total')::numeric<>0 then raise exception 'Composition bill of supply collected GST';end if;
  q:=public.gst_quote_v520(t,loc,'customer',customer,current_date,'B2C','32',items,0,0);
  if (q->>'ready_for_compliance')::boolean then raise exception 'Composition interstate outward supply accepted';end if;
  update public.gst_registration_versions_v520 set registration_type='regular' where registration_id=reg;
  update public.business_devices set invoice_prefix='INVALID_INVOICE_PREFIX' where id=device;
  bad:=false;begin perform public.gst_client_sale_create_v630(t,customer,current_date,current_date,items,'[{"method_code":"cash","amount":118}]','Invalid numbering',loc,device,gen_random_uuid()::text,'B2C','27','[]');exception when others then if sqlerrm not like '%16 letters%' then raise;end if;bad:=true;end;
  if not bad then raise exception 'Invalid legal invoice number accepted';end if;
  update public.business_devices set invoice_prefix='TST' where id=device;
  checks:=checks||jsonb_build_object('hsn_sac_and_b2b_recipient_guards','PASS','composition_bill_of_supply_and_interstate_guard','PASS','legal_invoice_number_guard','PASS');
  request:=gen_random_uuid()::text;
  r:=public.gst_client_sale_create_v630(t,customer,current_date,current_date,items,'[{"method_code":"cash","amount":118}]','Rollback registered invoice',loc,device,request,'B2C','27','[]');sale:=(r->>'sale_id')::uuid;
  q:=public.sales_get_detail_v630(t,sale);
  if (q->'gst'->>'cgst_total')::numeric<>9 or (q->'gst'->>'sgst_total')::numeric<>9 or q->'gst'->>'supplier_gstin'<>'27AAPFU0939F1ZV' or q->'gst'->>'supplier_legal_name'<>'Rollback registered business' then raise exception 'Saved registered invoice fields failed: %',q->'gst';end if;
  if (r->>'grand_total')::numeric<>118 or (select grand_total from public.gst_document_snapshots_v520 where id=(r->>'gst_snapshot_id')::uuid)<>118 or (select grand_total from public.sales where id=sale)<>118 then raise exception 'Registered invoice/snapshot total mismatch';end if;
  if exists(select 1 from public.journal_lines where journal_entry_id=(r->>'journal_id')::uuid group by journal_entry_id having abs(sum(debit-credit))>.005) then raise exception 'Registered journal imbalance';end if;
  update public.business_devices set invoice_prefix=null where id=device;
  request:=gen_random_uuid()::text;
  r:=public.gst_client_sale_create_v630(t,customer,current_date,current_date,items,'[{"method_code":"cash","amount":118}]','Inherited default numbering',loc,device,request,'B2C','27','[]');
  again:=public.gst_client_sale_create_v630(t,customer,current_date,current_date,items,'[{"method_code":"cash","amount":118}]','Inherited default numbering',loc,device,request,'B2C','27','[]');
  if length(r->>'invoice_number')>16 or r->>'invoice_number'!~'^[A-Za-z0-9/-]+$' or again->>'invoice_number'<>r->>'invoice_number' then raise exception 'Inherited default legal numbering or retry failed';end if;
  if has_table_privilege('authenticated','public.gst_invoice_series_v632','select') or has_function_privilege('authenticated','private.sale_default_legal_number_v632(uuid,uuid,uuid,text,date)','execute') then raise exception 'Numbering series privileges exposed';end if;
  checks:=checks||jsonb_build_object('inherited_default_number_and_retry','PASS','numbering_series_acl','PASS');
  insert into public.gst_tenant_tax_modes_v520(tenant_id,tax_mode,effective_from,effective_to,reason) values(t,'non_gst',current_date-1,current_date-1,'Historical unregistered fixture');
  if private.gst_tax_mode_resolve_v520(t,current_date-1)<>'non_gst' or private.gst_tax_mode_resolve_v520(t,current_date)<>'gst_registered' then raise exception 'Historical mode resolution changed';end if;
  update public.gst_tenant_tax_modes_v520 set effective_to=current_date where tenant_id=t and tax_mode='gst_registered';
  if private.gst_tax_mode_resolve_v520(t,current_date+1)<>'unconfigured' then raise exception 'Registration evidence silently became non-GST';end if;
  checks:=checks||jsonb_build_object('dated_modes_and_registration_evidence','PASS','registered_invoice_snapshot_and_balanced_journal','PASS');
  checks:=checks||jsonb_build_object('registered_missing_setup_blocked','PASS','cgst_sgst_and_igst','PASS','profile_review_blocked','PASS','inactive_or_unreviewed_registration_blocked','PASS','registered_sale_saved_gstin_name_and_components','PASS');
  raise exception using errcode='ZT001',message='Rollback all invoice fixtures';
 exception when sqlstate 'ZT001' then null;end;
 perform set_config('thq_v632_invoice_test.result',checks::text,false);
end $test$;
select current_setting('thq_v632_invoice_test.result')::jsonb as tests;
