-- Synthetic fixtures are rolled back inside the DO block. No client records are edited.
do $test$
declare t uuid:=gen_random_uuid();usr uuid:=gen_random_uuid();membership uuid:=gen_random_uuid();role_id uuid;loc uuid:=gen_random_uuid();loc2 uuid:=gen_random_uuid();device uuid:=gen_random_uuid();customer uuid:=gen_random_uuid();supplier uuid:=gen_random_uuid();prod uuid:=gen_random_uuid();v uuid:=gen_random_uuid();unit uuid:=gen_random_uuid();
 p jsonb;r jsonb;again jsonb;alloc jsonb;items jsonb;source_item uuid;batch_sale uuid;batch_item uuid;bid uuid;serial_sale uuid;serial_item uuid;purchase_id uuid;purchase_item uuid;purchase_batch uuid;before_qty numeric;before_cost numeric;before_journals integer;before_trace integer;request text;bad boolean;checks jsonb:='{}';
begin
 begin
  insert into public.tenants(id,name,slug,business_type) values(t,'Tracking rollback store','tracking-rollback-'||t,'material_yard');
  insert into auth.users(id,aud,role,email) values(usr,'authenticated','authenticated','tracking-rollback-'||usr||'@example.invalid');
  insert into public.tenant_memberships(id,tenant_id,user_id) values(membership,t,usr);
  select id into role_id from public.roles where tenant_id=t and key='owner' limit 1;
  if role_id is null then insert into public.roles(tenant_id,key,name) values(t,'owner','Owner') returning id into role_id;end if;
  insert into public.role_permissions(role_id,permission_key) select role_id,key from public.permissions on conflict do nothing;
  insert into public.user_roles(tenant_id,membership_id,role_id) values(t,membership,role_id);
  perform set_config('request.jwt.claim.sub',usr::text,true);
  perform private.v491_ensure_financial_mappings(t);perform private.v628_seed_payment_methods(t);
  insert into public.business_locations(id,tenant_id,location_code,name,invoice_prefix,state,address_line1) values(loc,t,'ROLLBACK-'||loc,'Tracking branch','TST','Maharashtra','Test address');
  insert into public.business_devices(id,tenant_id,location_id,device_code,name,app_type,status,invoice_prefix) values(device,t,loc,'ROLLBACK-'||device,'Tracking client','client','active','TST');
  insert into public.customers(id,tenant_id,name,state,is_walk_in) values(customer,t,'Tracking customer','Maharashtra',false);
  insert into public.suppliers(id,tenant_id,name) values(supplier,t,'Tracking supplier');
  insert into public.inventory_units_v481(id,tenant_id,code,name) values(unit,t,'TESTUNIT','Test unit');
  insert into public.products(id,tenant_id,name,item_type,base_unit_id,tax_rate) values(prod,t,'Tracking product','stock',unit,0);
  insert into public.product_variants(id,tenant_id,product_id,name,sku,selling_price,cost_price) values(v,t,prod,'Default','ROLLBACK-'||v,100,10);
  insert into public.product_units_v481(tenant_id,variant_id,unit_id,is_base,is_default_sale,allow_sale,is_default_purchase,allow_purchase) values(t,v,unit,true,true,true,true,true);
  perform public.inventory_location_assign_v4(t,loc,v,true,100,0,null);
  perform public.inventory_adjust_stock(t,v,600,'Rollback opening');
  insert into public.location_stock_balances(tenant_id,location_id,variant_id,quantity,average_cost) values(t,loc,v,600,10) on conflict(tenant_id,location_id,variant_id) do update set quantity=600,average_cost=10;
  items:=jsonb_build_array(jsonb_build_object('variant_id',v,'unit_id',unit,'quantity',1,'unit_price',100,'discount_amount',0,'tax_rate',0,'thq_manual_price_v630',true));
  r:=public.gst_client_sale_create_v630(t,customer,current_date,current_date,items,'[{"method_code":"cash","amount":100}]','Rollback untracked sale',loc,device,gen_random_uuid()::text,null,null,'[]');
  select id into source_item from public.sale_items where sale_id=(r->>'sale_id')::uuid;
  if private.tracking_source_v633(t,'sale',source_item)->>'mode'<>'none' then raise exception 'Original untracked sale mode not saved';end if;
  p:=public.inventory_tracking_conversion_preview_v633(t,v);
  alloc:=jsonb_build_array(jsonb_build_object('location_id',loc,'expected_quantity',599,'batches',jsonb_build_array(jsonb_build_object('batch_number','CONVERT-A','quantity',599))));
  select quantity,average_cost into before_qty,before_cost from public.location_stock_balances where tenant_id=t and location_id=loc and variant_id=v;
  select count(*) into before_journals from public.journal_entries where tenant_id=t;
  request:=gen_random_uuid()::text;
  r:=public.inventory_tracking_convert_v633(t,v,'batch',0,alloc,'Start batch tracking',request,true);
  again:=public.inventory_tracking_convert_v633(t,v,'batch',0,alloc,'Start batch tracking',request,true);
  if not (again->>'idempotent_replay')::boolean or again->>'conversion_id'<>r->>'conversion_id' then raise exception 'Conversion retry failed';end if;
  if exists(select 1 from public.location_stock_balances where tenant_id=t and location_id=loc and variant_id=v and (quantity<>before_qty or average_cost<>before_cost)) or (select count(*) from public.journal_entries where tenant_id=t)<>before_journals then raise exception 'Conversion changed ledger or value';end if;
  bad:=false;begin perform public.inventory_tracking_convert_v633(t,v,'none',1,'[]','Different request',request,true);exception when others then if sqlerrm not like '%different conversion%' then raise;end if;bad:=true;end;if not bad then raise exception 'Mismatched retry accepted';end if;
  bad:=false;begin perform public.inventory_tracking_policy_save_v483(t,v,'none',false,0,0,false,false);exception when others then if sqlerrm not like '%Change Tracking Method%' then raise;end if;bad:=true;end;if not bad then raise exception 'Old policy RPC bypassed conversion';end if;
  bad:=false;begin perform private.tracking_assert_payload_v633(t,items,true);exception when others then if sqlerrm not like '%Tracking changed%' then raise;end if;bad:=true;end;if not bad then raise exception 'Stale offline invoice accepted';end if;
  perform private.tracking_assert_payload_v633(t,jsonb_set(items,'{0,tracking_revision}','1'),true);
  checks:=checks||jsonb_build_object('quantity_value_and_journals_preserved','PASS','idempotent_conversion_and_mismatch','PASS','old_rpc_bypass_blocked','PASS','offline_revision_guard','PASS');
  select sale_id into batch_sale from public.sale_items where id=source_item;
  r:=public.gst_sales_return_create_v520(t,batch_sale,current_date,jsonb_build_array(jsonb_build_object('sale_item_id',source_item,'quantity',1)),'Return old untracked invoice',loc,device,gen_random_uuid()::text);
  perform private.v483_assert_reconciled(t,v,loc);
  if (select quantity from public.location_stock_balances where tenant_id=t and location_id=loc and variant_id=v)<>600 then raise exception 'Old untracked return changed stock incorrectly';end if;
  select id into bid from public.inventory_batches_v483 where tenant_id=t and batch_number='CONVERT-A';
  items:=jsonb_build_array(jsonb_build_object('variant_id',v,'unit_id',unit,'quantity',2,'unit_price',100,'discount_amount',0,'tax_rate',0,'batches',jsonb_build_array(jsonb_build_object('batch_id',bid,'quantity',2)),'thq_manual_price_v630',true,'tracking_revision',1));
  r:=public.gst_client_sale_create_v630(t,customer,current_date,current_date,items,'[{"method_code":"cash","amount":200}]','Rollback batch sale',loc,device,gen_random_uuid()::text,null,null,'[]');batch_sale:=(r->>'sale_id')::uuid;
  select id into batch_item from public.sale_items where sale_id=batch_sale;
  select count(*) into before_trace from public.inventory_trace_events_v483 where tenant_id=t and sale_item_id=batch_item;
  p:=public.inventory_tracking_conversion_preview_v633(t,v);
  alloc:=jsonb_build_array(jsonb_build_object('location_id',loc,'expected_quantity',598));
  r:=public.inventory_tracking_convert_v633(t,v,'none',1,alloc,'Stop batch tracking',gen_random_uuid()::text,true);
  if (select count(*) from public.inventory_trace_events_v483 where tenant_id=t and sale_item_id=batch_item)<>before_trace then raise exception 'Old invoice trace was removed';end if;
  perform public.inventory_tracking_policy_save_v483(t,v,'none',false,0,0,false,false);
  r:=public.gst_sales_return_create_v520(t,batch_sale,current_date,jsonb_build_array(jsonb_build_object('sale_item_id',batch_item,'quantity',1,'batches',jsonb_build_array(jsonb_build_object('batch_id',bid,'quantity',1)))),'Return old batch invoice',loc,device,gen_random_uuid()::text);
  if (select quantity from public.location_stock_balances where tenant_id=t and location_id=loc and variant_id=v)<>599 or (select coalesce(sum(bb.quantity),0) from public.inventory_batch_balances_v483 bb where bb.tenant_id=t)<>0 then raise exception 'Old batch return restored obsolete batch allocation';end if;
  checks:=checks||jsonb_build_object('old_untracked_return_into_batch','PASS','old_batch_return_into_untracked','PASS','old_invoice_trace_preserved','PASS','settings_after_disable','PASS');
  -- Serial conversion, immutable warranties, and a return across two later modes.
  select jsonb_build_array(jsonb_build_object('location_id',loc,'expected_quantity',599,'serial_numbers',(select jsonb_agg('S-'||n order by n) from generate_series(1,599) n))) into alloc;
  r:=public.inventory_tracking_convert_v633(t,v,'serial',2,alloc,'Start serial tracking',gen_random_uuid()::text,true,'{"warranty_enabled":true,"warranty_months":12}');
  items:=jsonb_build_array(jsonb_build_object('variant_id',v,'unit_id',unit,'quantity',2,'unit_price',100,'discount_amount',0,'tax_rate',0,'serial_numbers','["S-1","S-2"]'::jsonb,'thq_manual_price_v630',true,'tracking_revision',3));
  r:=public.gst_client_sale_create_v630(t,customer,current_date,current_date,items,'[{"method_code":"cash","amount":200}]','Rollback serial sale',loc,device,gen_random_uuid()::text,null,null,'[]');serial_sale:=(r->>'sale_id')::uuid;
  select id into serial_item from public.sale_items where sale_id=serial_sale;
  if (select count(*) from public.product_warranties_v483 where tenant_id=t and sale_item_id=serial_item and status='active')<>2 then raise exception 'Serial warranty fixture failed';end if;
  alloc:=jsonb_build_array(jsonb_build_object('location_id',loc,'expected_quantity',597,'batches',jsonb_build_array(jsonb_build_object('batch_number','CONVERT-B','quantity',597))));
  r:=public.inventory_tracking_convert_v633(t,v,'batch',3,alloc,'Serial to batch tracking',gen_random_uuid()::text,true);
  r:=public.gst_sales_return_create_v520(t,serial_sale,current_date,jsonb_build_array(jsonb_build_object('sale_item_id',serial_item,'quantity',1,'serial_numbers','["S-1"]'::jsonb)),'Return original serial',loc,device,gen_random_uuid()::text);
  perform private.v483_assert_reconciled(t,v,loc);
  if (select count(*) from public.product_warranties_v483 where tenant_id=t and sale_item_id=serial_item and status='active')<>1 then raise exception 'Wrong original warranty was voided';end if;
  bad:=false;begin perform public.gst_sales_return_create_v520(t,serial_sale,current_date,jsonb_build_array(jsonb_build_object('sale_item_id',serial_item,'quantity',1,'serial_numbers','["S-1"]'::jsonb)),'Duplicate original serial',loc,device,gen_random_uuid()::text);exception when others then if sqlerrm not like '%already returned%' then raise;end if;bad:=true;end;if not bad then raise exception 'An original serial was returned twice';end if;
  checks:=checks||jsonb_build_object('serial_to_batch_conversion','PASS','original_serial_return_and_warranty','PASS','duplicate_serial_return_blocked','PASS');
  items:=jsonb_build_array(jsonb_build_object('variant_id',v,'unit_id',unit,'quantity',2,'unit_cost',10,'discount_amount',0,'tax_rate',0,'batches',jsonb_build_array(jsonb_build_object('batch_number','PURCHASE-A','quantity',2,'purchase_cost_base',10))));
  r:=public.gst_purchase_create_v520(p_tenant_id:=t,p_supplier_id:=supplier,p_supplier_invoice_number:='ROLLBACK-PUR',p_purchase_date:=current_date,p_due_date:=current_date,p_items:=items,p_location_id:=loc,p_device_id:=device,p_request_id:=gen_random_uuid()::text);
  purchase_id:=(r->>'purchase_id')::uuid;select id into purchase_item from public.purchase_items where public.purchase_items.purchase_id=(r->>'purchase_id')::uuid;
  select id into purchase_batch from public.inventory_batches_v483 where tenant_id=t and batch_number='PURCHASE-A';
  alloc:=jsonb_build_array(jsonb_build_object('location_id',loc,'expected_quantity',600));
  r:=public.inventory_tracking_convert_v633(t,v,'none',4,alloc,'Pool current batch stock',gen_random_uuid()::text,true);
  select jsonb_build_array(jsonb_build_object('location_id',loc,'expected_quantity',600,'serial_numbers',(select jsonb_agg('X-'||n order by n) from generate_series(1,600) n))) into alloc;
  r:=public.inventory_tracking_convert_v633(t,v,'serial',5,alloc,'Identify current stock',gen_random_uuid()::text,true);
  r:=public.gst_purchase_return_create_v520(t,purchase_id,current_date,jsonb_build_array(jsonb_build_object('purchase_item_id',purchase_item,'quantity',1,'batches',jsonb_build_array(jsonb_build_object('batch_id',purchase_batch,'quantity',1)),'current_serial_numbers','["X-1"]'::jsonb)),'Return supplier goods',loc,device,gen_random_uuid()::text);
  perform private.v483_assert_reconciled(t,v,loc);
  if (select quantity from public.location_stock_balances where tenant_id=t and location_id=loc and variant_id=v)<>599 then raise exception 'Supplier return removed stock twice';end if;
  r:=public.gst_sales_return_create_v520(t,serial_sale,current_date,jsonb_build_array(jsonb_build_object('sale_item_id',serial_item,'quantity',1,'serial_numbers','["S-2"]'::jsonb)),'Restore second original serial',loc,device,gen_random_uuid()::text);
  perform private.v483_assert_reconciled(t,v,loc);
  if (select quantity from public.location_stock_balances where tenant_id=t and location_id=loc and variant_id=v)<>600 then raise exception 'Original serial return after multiple conversions failed';end if;
  if exists(select 1 from public.journal_lines j join public.journal_entries e on e.id=j.journal_entry_id where e.tenant_id=t group by e.id having abs(sum(j.debit-j.credit))>.005) then raise exception 'Invoice/return journal imbalance';end if;
  checks:=checks||jsonb_build_object('batch_to_serial_through_untracked','PASS','supplier_return_source_and_current_allocation','PASS','original_serial_return_after_multiple_conversions','PASS','invoice_and_return_journals_balanced','PASS');
  -- Stale preview, fractional serials, reservations and anonymous/other-tenant access.
  bad:=false;begin perform public.inventory_tracking_convert_v633(t,v,'batch',1,alloc,'Stale tracking revision',gen_random_uuid()::text,true);exception when others then if sqlerrm not like '%Reload%' then raise;end if;bad:=true;end;if not bad then raise exception 'Stale preview accepted';end if;
  update public.location_stock_balances set reserved_quantity=1 where tenant_id=t and location_id=loc and variant_id=v;
  p:=public.inventory_tracking_conversion_preview_v633(t,v);if (p->>'ready')::boolean then raise exception 'Reserved stock conversion enabled';end if;
  update public.location_stock_balances set reserved_quantity=0 where tenant_id=t and location_id=loc and variant_id=v;
  perform set_config('request.jwt.claim.sub','',true);
  bad:=false;begin perform public.inventory_tracking_conversion_preview_v633(t,v);exception when sqlstate '42501' then bad:=true;end;if not bad then raise exception 'Anonymous preview accepted';end if;
  perform set_config('request.jwt.claim.sub',usr::text,true);
  bad:=false;begin perform public.inventory_tracking_conversion_preview_v633(gen_random_uuid(),v);exception when sqlstate '42501' then bad:=true;end;if not bad then raise exception 'Other tenant preview accepted';end if;
  if has_function_privilege('anon','public.inventory_tracking_convert_v633(uuid,uuid,text,integer,jsonb,text,text,boolean,jsonb)','execute') or has_function_privilege('authenticated','private.tracking_bridge_return_v633(uuid,text,uuid,uuid,jsonb)','execute') then raise exception 'Helper or anonymous permissions exposed';end if;
  checks:=checks||jsonb_build_object('reservation_and_stale_preview_guards','PASS','tenant_and_anonymous_guards','PASS');
  -- A second branch and fractional quantities must stay intact across conversions.
  insert into public.business_locations(id,tenant_id,location_code,name,state) values(loc2,t,'ROLLBACK-2-'||loc2,'Second tracking branch','Maharashtra');
  perform public.inventory_location_assign_v4(t,loc2,v,true,100,0,null);
  update public.location_stock_balances set quantity=599 where tenant_id=t and location_id=loc and variant_id=v;
  update public.inventory_serials_v483 set current_location_id=loc2 where tenant_id=t and variant_id=v and serial_number='S-2';
  insert into public.location_stock_balances(tenant_id,location_id,variant_id,quantity,average_cost) values(t,loc2,v,1,10) on conflict(tenant_id,location_id,variant_id) do update set quantity=1,average_cost=10;
  alloc:=jsonb_build_array(jsonb_build_object('location_id',loc,'expected_quantity',599,'batches',jsonb_build_array(jsonb_build_object('batch_number','MULTI-A','quantity',599))),jsonb_build_object('location_id',loc2,'expected_quantity',1,'batches',jsonb_build_array(jsonb_build_object('batch_number','MULTI-B','quantity',1))));
  perform public.inventory_tracking_convert_v633(t,v,'batch',6,alloc,'Multiple branch conversion',gen_random_uuid()::text,true);
  if private.v483_location_tracked_quantity(t,v,loc,'batch')<>599 or private.v483_location_tracked_quantity(t,v,loc2,'batch')<>1 then raise exception 'Multi-branch conversion mixed stock';end if;
  alloc:=jsonb_build_array(jsonb_build_object('location_id',loc,'expected_quantity',599,'serial_numbers',(select jsonb_agg('Y'||i) from generate_series(1,599) i)),jsonb_build_object('location_id',loc2,'expected_quantity',1,'serial_numbers','["BRANCH2"]'::jsonb));
  perform public.inventory_tracking_convert_v633(t,v,'serial',7,alloc,'Direct batch to serial',gen_random_uuid()::text,true);
  if private.v483_location_tracked_quantity(t,v,loc,'serial')<>599 or private.v483_location_tracked_quantity(t,v,loc2,'serial')<>1 then raise exception 'Direct batch to serial failed';end if;
  alloc:=jsonb_build_array(jsonb_build_object('location_id',loc,'expected_quantity',599),jsonb_build_object('location_id',loc2,'expected_quantity',1));
  perform public.inventory_tracking_convert_v633(t,v,'none',8,alloc,'Fractional conversion preparation',gen_random_uuid()::text,true);
  update public.location_stock_balances set quantity=598.5 where tenant_id=t and location_id=loc and variant_id=v;
  alloc:=jsonb_build_array(jsonb_build_object('location_id',loc,'expected_quantity',598.5,'serial_numbers','[]'::jsonb),jsonb_build_object('location_id',loc2,'expected_quantity',1,'serial_numbers','["FRACTION2"]'::jsonb));
  bad:=false;begin perform public.inventory_tracking_convert_v633(t,v,'serial',9,alloc,'Reject fractional serial quantities',gen_random_uuid()::text,true);exception when others then if sqlerrm not like '%whole base unit%' then raise;end if;bad:=true;end;
  if not bad or private.v483_tracking_mode(t,v)<>'none' or (select tracking_revision from public.product_tracking_policies_v483 where tenant_id=t and variant_id=v)<>9 then raise exception 'Rejected fractional conversion was not atomic';end if;
  alloc:=jsonb_build_array(jsonb_build_object('location_id',loc,'expected_quantity',598.5,'batches',jsonb_build_array(jsonb_build_object('batch_number','FRACTION-A','quantity',598.5))),jsonb_build_object('location_id',loc2,'expected_quantity',1,'batches',jsonb_build_array(jsonb_build_object('batch_number','FRACTION-B','quantity',1))));
  perform public.inventory_tracking_convert_v633(t,v,'batch',9,alloc,'Accept fractional batch quantities',gen_random_uuid()::text,true);
  if private.v483_location_tracked_quantity(t,v,loc,'batch')<>598.5 then raise exception 'Fractional batch quantities lost';end if;
  checks:=checks||jsonb_build_object('multiple_branches_preserved','PASS','direct_batch_to_serial','PASS','fractional_validation_and_atomic_rollback','PASS');
  p:=public.inventory_tracking_policy_v483(t,v);
  if (p->>'tracking_revision')::integer is distinct from 10 then raise exception 'Policy did not expose conversion revision';end if;
  select x into p from public.inventory_list_products_v483(t,loc) as f(x) where x->>'variant_id'=v::text;
  if (p->>'tracking_revision')::integer is distinct from 10 then raise exception 'Product catalogue did not expose conversion revision';end if;
  update public.business_devices set app_type='pos' where id=device;
  select x into p from jsonb_array_elements(public.pos_offline_product_cache_v486(t,device)) x where x->>'variant_id'=v::text;
  if (p->>'tracking_revision')::integer is distinct from 10 then raise exception 'POS cache lost conversion revision';end if;
  select x into p from jsonb_array_elements(public.mobile_pos_product_cache_v520(t,device)) x where x->>'variant_id'=v::text;
  if (p->>'tracking_revision')::integer is distinct from 10 then raise exception 'Mobile cache lost conversion revision';end if;
  checks:=checks||jsonb_build_object('policy_catalogue_pos_mobile_revision','PASS');
  raise exception using errcode='P6331',message='Roll back synthetic tracking fixtures';
 exception when sqlstate 'P6331' then null;
 end;
 perform set_config('thq.tracking_test_results',checks::text,false);
end $test$;
select current_setting('thq.tracking_test_results')::jsonb as tracking_test_results;
