-- FLEXI ERP V4 richer analytics, GST and branch-aware top lists.
begin;
create or replace function public.analytics_top_products_v4(p_tenant_id uuid,p_from date,p_to date,p_location_id uuid default null,p_limit integer default 10)
returns table(variant_id uuid,product_name text,sku text,quantity numeric,revenue numeric,gross_profit numeric)
language plpgsql security definer set search_path=public,private,pg_temp as $$ begin if not private.erp_user_has_tenant_access(p_tenant_id) then raise exception 'Access denied';end if;return query select si.variant_id,max(pr.name),max(pv.sku),sum(si.quantity),sum(si.line_total),sum(coalesce(si.gross_profit,0)) from public.sale_items si join public.sales s on s.id=si.sale_id join public.product_variants pv on pv.id=si.variant_id join public.products pr on pr.id=pv.product_id left join public.document_origins o on o.entity_type='sale' and o.entity_id=s.id where s.tenant_id=p_tenant_id and s.sale_date between p_from and p_to and coalesce(s.status,'') not in('void','cancelled') and private.erp_document_scope_allowed(p_tenant_id,o.location_id,p_location_id,'view') group by si.variant_id order by sum(si.quantity) desc limit greatest(1,least(coalesce(p_limit,10),100));end $$;
grant execute on function public.analytics_top_products_v4(uuid,date,date,uuid,integer) to authenticated;

create or replace function public.analytics_top_customers_v4(p_tenant_id uuid,p_from date,p_to date,p_location_id uuid default null,p_limit integer default 10)
returns table(customer_id uuid,customer_name text,sale_count bigint,revenue numeric,balance_due numeric)
language plpgsql security definer set search_path=public,private,pg_temp as $$ begin if not private.erp_user_has_tenant_access(p_tenant_id) then raise exception 'Access denied';end if;return query select c.id,c.name,count(s.id),sum(s.grand_total),sum(greatest(s.grand_total-coalesce(py.paid,0),0)) from public.sales s join public.customers c on c.id=s.customer_id left join(select sale_id,sum(amount) paid from public.sale_payments group by sale_id)py on py.sale_id=s.id left join public.document_origins o on o.entity_type='sale' and o.entity_id=s.id where s.tenant_id=p_tenant_id and s.sale_date between p_from and p_to and coalesce(s.status,'') not in('void','cancelled') and private.erp_document_scope_allowed(p_tenant_id,o.location_id,p_location_id,'view') group by c.id,c.name order by sum(s.grand_total) desc limit greatest(1,least(coalesce(p_limit,10),100));end $$;
grant execute on function public.analytics_top_customers_v4(uuid,date,date,uuid,integer) to authenticated;

create or replace function public.gst_summary_v4(p_tenant_id uuid,p_from date,p_to date,p_location_id uuid default null)
returns jsonb language plpgsql security definer set search_path=public,private,pg_temp as $$ declare v_out numeric;v_in numeric;v_sales numeric;v_purchases numeric;begin if not private.erp_user_has_tenant_access(p_tenant_id) then raise exception 'Access denied';end if;select coalesce(sum(s.tax_total),0),coalesce(sum(s.taxable_total),0) into v_out,v_sales from public.sales s left join public.document_origins o on o.entity_type='sale' and o.entity_id=s.id where s.tenant_id=p_tenant_id and s.sale_date between p_from and p_to and coalesce(s.status,'') not in('void','cancelled') and private.erp_document_scope_allowed(p_tenant_id,o.location_id,p_location_id,'view');select coalesce(sum(p.tax_total),0),coalesce(sum(p.taxable_total),0) into v_in,v_purchases from public.purchases p left join public.document_origins o on o.entity_type='purchase' and o.entity_id=p.id where p.tenant_id=p_tenant_id and p.purchase_date between p_from and p_to and coalesce(p.status,'') not in('void','cancelled') and private.erp_document_scope_allowed(p_tenant_id,o.location_id,p_location_id,'view');return jsonb_build_object('taxable_sales',v_sales,'output_gst',v_out,'taxable_purchases',v_purchases,'input_gst',v_in,'net_gst_payable',v_out-v_in);end $$;
grant execute on function public.gst_summary_v4(uuid,date,date,uuid) to authenticated;

create or replace function public.inventory_branch_low_stock_v4(p_tenant_id uuid,p_location_id uuid default null,p_limit integer default 50)
returns table(location_id uuid,location_code text,variant_id uuid,product_name text,sku text,quantity numeric,reorder_level numeric)
language plpgsql security definer set search_path=public,private,pg_temp as $$ begin if not private.erp_user_has_tenant_access(p_tenant_id) then raise exception 'Access denied';end if;return query select l.id,l.location_code,pv.id,p.name,pv.sku,coalesce(b.quantity,0),coalesce(s.reorder_level,pv.reorder_level,0) from public.location_product_settings s join public.business_locations l on l.id=s.location_id join public.product_variants pv on pv.id=s.variant_id join public.products p on p.id=pv.product_id left join public.location_stock_balances b on b.tenant_id=s.tenant_id and b.location_id=s.location_id and b.variant_id=s.variant_id where s.tenant_id=p_tenant_id and s.active and l.active and (p_location_id is null or l.id=p_location_id) and private.erp_document_scope_allowed(p_tenant_id,l.id,p_location_id,'view') and coalesce(s.reorder_level,pv.reorder_level,0)>0 and coalesce(b.quantity,0)<=coalesce(s.reorder_level,pv.reorder_level,0) order by (coalesce(b.quantity,0)-coalesce(s.reorder_level,pv.reorder_level,0)),p.name limit greatest(1,least(coalesce(p_limit,50),500));end $$;
grant execute on function public.inventory_branch_low_stock_v4(uuid,uuid,integer) to authenticated;
commit;
select 'Flexi ERP V4 analytics/GST ready' as status;
