-- THQ ERP v5.0.0 — milestone dashboard / business intelligence.
begin;
create or replace function public.dashboard_business_intelligence_v500(p_tenant_id uuid,p_location_id uuid default null,p_day date default current_date)
returns jsonb language plpgsql stable security definer set search_path=public,private,pg_temp as $$
declare
  sales numeric:=0; returns numeric:=0; cost numeric:=0; expenses numeric:=0; receivable numeric:=0; payable numeric:=0;
  low_stock bigint:=0; dead_stock bigint:=0; best jsonb:='[]'::jsonb; slow jsonb:='[]'::jsonb; stores jsonb:='[]'::jsonb; pos jsonb:='[]'::jsonb; hourly jsonb:='[]'::jsonb;
begin
  if not private.erp_user_has_tenant_access(p_tenant_id) then raise exception 'Access denied';end if;
  select coalesce(sum(grand_total),0),coalesce(sum(cost_total),0) into sales,cost from public.sales where tenant_id=p_tenant_id and sale_date=p_day and coalesce(status,'') not in('void','cancelled') and (p_location_id is null or location_id=p_location_id);
  select coalesce(sum(r.grand_total),0) into returns from public.sales_returns r where r.tenant_id=p_tenant_id and r.return_date=p_day and r.refund_status<>'waived' and (p_location_id is null or r.location_id=p_location_id);
  select coalesce(sum(total_amount),0) into expenses from public.expenses e left join public.document_origins o on o.tenant_id=e.tenant_id and o.entity_type='expense' and o.entity_id=e.id where e.tenant_id=p_tenant_id and e.expense_date=p_day and e.status='posted' and (p_location_id is null or o.location_id=p_location_id);
  select coalesce(sum(balance),0) into receivable from (select greatest(s.grand_total-coalesce(rt.x,0)-coalesce(py.x,0),0) balance from public.sales s left join(select sale_id,sum(grand_total)x from public.sales_returns where refund_status<>'waived' group by sale_id)rt on rt.sale_id=s.id left join(select sale_id,sum(amount)x from public.sale_payments group by sale_id)py on py.sale_id=s.id where s.tenant_id=p_tenant_id and coalesce(s.status,'') not in('void','cancelled') and (p_location_id is null or s.location_id=p_location_id))q;
  select coalesce(sum(balance),0) into payable from (select greatest(p.grand_total-coalesce(rt.x,0)-coalesce(py.x,0),0) balance from public.purchases p left join(select purchase_id,sum(grand_total)x from public.purchase_returns where credit_status<>'waived' group by purchase_id)rt on rt.purchase_id=p.id left join(select purchase_id,sum(amount)x from public.purchase_payments group by purchase_id)py on py.purchase_id=p.id where p.tenant_id=p_tenant_id and coalesce(p.status,'') not in('void','cancelled') and (p_location_id is null or p.location_id=p_location_id) union all select greatest(i.balance_due,0) from public.purchase_invoices_v484 i where i.tenant_id=p_tenant_id and i.status in('posted','part_paid') and (p_location_id is null or i.location_id=p_location_id))q;
  select count(*) filter(where status in('low_stock','out_of_stock')),count(*) filter(where status='dead_stock') into low_stock,dead_stock from public.inventory_intelligence_v480(p_tenant_id,p_location_id,30,'',5000);
  select coalesce(jsonb_agg(to_jsonb(q)),'[]'::jsonb) into best from (select pr.name product_name,sum(si.quantity) quantity,sum(si.line_total) sales_value from public.sale_items si join public.sales s on s.id=si.sale_id join public.product_variants pv on pv.id=si.variant_id join public.products pr on pr.id=pv.product_id where s.tenant_id=p_tenant_id and s.sale_date between p_day-29 and p_day and coalesce(s.status,'') not in('void','cancelled') and (p_location_id is null or s.location_id=p_location_id) group by pr.id,pr.name order by quantity desc limit 10)q;
  select coalesce(jsonb_agg(to_jsonb(q)),'[]'::jsonb) into stores from (select l.id location_id,l.name,coalesce(sum(s.grand_total),0) gross_sales from public.business_locations l left join public.sales s on s.location_id=l.id and s.tenant_id=p_tenant_id and s.sale_date=p_day and coalesce(s.status,'') not in('void','cancelled') where l.tenant_id=p_tenant_id group by l.id,l.name order by gross_sales desc)q;
  select coalesce(jsonb_agg(to_jsonb(q)),'[]'::jsonb) into hourly from (select extract(hour from created_at)::int hour,round(sum(grand_total),2) sales from public.sales where tenant_id=p_tenant_id and sale_date=p_day and coalesce(status,'') not in('void','cancelled') and (p_location_id is null or location_id=p_location_id) group by 1 order by 1)q;
  return jsonb_build_object('day',p_day,'net_sales',round(sales-returns,2),'gross_sales',round(sales,2),'sales_returns',round(returns,2),'gross_profit',round((sales-returns)-cost,2),'gross_margin_pct',case when sales-returns>0 then round(((sales-returns)-cost)*100/(sales-returns),2) else 0 end,'expenses',round(expenses,2),'estimated_profit',round((sales-returns)-cost-expenses,2),'receivables',round(receivable,2),'payables',round(payable,2),'low_stock_count',low_stock,'dead_stock_count',dead_stock,'best_sellers',best,'store_comparison',stores,'hourly_sales',hourly);
end $$;
grant execute on function public.dashboard_business_intelligence_v500(uuid,uuid,date) to authenticated;
insert into public.thq_schema_releases(migration_no,schema_version,release_name,notes) values(207,'5.0.0','Dashboard & Business Intelligence','Return-aware sales/profit, dues, stock risk, best sellers, store comparison and hourly trends.') on conflict(migration_no) do update set schema_version=excluded.schema_version,release_name=excluded.release_name,notes=excluded.notes;
commit;
select 'THQ ERP v5.0.0 migration 207 applied' as status;
