import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../services/device_installation_service.dart';
import '../services/mobile_pos_auth_service.dart';
import '../services/mobile_pos_session_service.dart';
import 'mobile_pos_home_screen.dart';
class MobilePosEntryScreen extends StatefulWidget {const MobilePosEntryScreen({super.key});@override State<MobilePosEntryScreen> createState()=>_State();}
class _State extends State<MobilePosEntryScreen>{late Future<DeviceActivation?> _activation;@override void initState(){super.initState();_activation=DeviceInstallationService().readActivation();}@override Widget build(BuildContext context)=>FutureBuilder<DeviceActivation?>(future:_activation,builder:(context,s){if(s.connectionState!=ConnectionState.done)return const Scaffold(body:Center(child:CircularProgressIndicator()));if(s.data==null)return _Activation(onDone:()=>setState(()=>_activation=DeviceInstallationService().readActivation()));if(Supabase.instance.client.auth.currentSession==null)return _Login(onDone:()=>setState((){}));return const _Session();});}
class _Activation extends StatefulWidget {final VoidCallback onDone;const _Activation({required this.onDone});@override State<_Activation> createState()=>_ActivationState();}
class _ActivationState extends State<_Activation>{final b=TextEditingController(),c=TextEditingController();bool busy=false;String? error;@override void dispose(){b.dispose();c.dispose();super.dispose();}Future<void> go()async{if(busy)return;setState(()=>busy=true);try{await DeviceInstallationService().activate(businessCode:b.text,activationCode:c.text);widget.onDone();}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:ListView(padding:const EdgeInsets.all(24),children:[const SizedBox(height:48),const Icon(Icons.point_of_sale,size:70),const SizedBox(height:16),Text('THQ Mobile POS',textAlign:TextAlign.center,style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:8),const Text('Activate this phone using a POS terminal activation code from THQ Admin.',textAlign:TextAlign.center),const SizedBox(height:28),TextField(controller:b,textCapitalization:TextCapitalization.characters,decoration:const InputDecoration(labelText:'Business code',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:c,textCapitalization:TextCapitalization.characters,decoration:const InputDecoration(labelText:'Activation code',border:OutlineInputBorder())),if(error!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error))),const SizedBox(height:16),FilledButton.icon(onPressed:busy?null:go,icon:const Icon(Icons.phonelink_lock),label:Text(busy?'Activating...':'Activate Mobile POS'))])));}
class _Login extends StatefulWidget {final VoidCallback onDone;const _Login({required this.onDone});@override State<_Login> createState()=>_LoginState();}
class _LoginState extends State<_Login>{final u=TextEditingController(),p=TextEditingController();bool busy=false;String? error;@override void dispose(){u.dispose();p.dispose();super.dispose();}Future<void> go()async{if(busy)return;setState(()=>busy=true);try{await MobilePosAuthService().signIn(username:u.text,password:p.text);widget.onDone();}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:ListView(padding:const EdgeInsets.all(24),children:[const SizedBox(height:48),const Icon(Icons.badge_outlined,size:64),const SizedBox(height:18),Text('POS sign in',style:Theme.of(context).textTheme.headlineMedium,textAlign:TextAlign.center),const SizedBox(height:24),TextField(controller:u,decoration:const InputDecoration(labelText:'Username',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:p,obscureText:true,onSubmitted:(_)=>go(),decoration:const InputDecoration(labelText:'Password',border:OutlineInputBorder())),if(error!=null)Padding(padding:const EdgeInsets.only(top:12),child:Text(error!,style:TextStyle(color:Theme.of(context).colorScheme.error))),const SizedBox(height:16),FilledButton(onPressed:busy?null:go,child:Text(busy?'Signing in...':'Sign in'))])));}
class _Session extends StatelessWidget {const _Session();@override Widget build(BuildContext context)=>FutureBuilder(future:MobilePosSessionService().load(),builder:(context,s){if(s.connectionState!=ConnectionState.done)return const Scaffold(body:Center(child:CircularProgressIndicator()));if(s.hasError)return Scaffold(body:Center(child:Padding(padding:const EdgeInsets.all(24),child:Text(s.error.toString()))));return MobilePosHomeScreen(session:s.data!);});}
