begin;
create or replace function private.gst_source_assert_v520(p_tenant_id uuid,p_source_type text,p_source_id uuid,p_source_number text,p_document_date date,p_location_id uuid,p_links jsonb) returns void
language plpgsql stable security definer set search_path=public,private,pg_temp as $$
declare n text;d date;l uuid;missing_count integer:=0;
begin
 if p_source_type='sale' then
  select s.sale_number,s.sale_date,o.location_id into n,d,l from public.sales s left join public.document_origins o on o.tenant_id=s.tenant_id and o.entity_type='sale' and o.entity_id=s.id where s.tenant_id=p_tenant_id and s.id=p_source_id and s.status='posted';
  if n is not null then select count(*) into missing_count from jsonb_array_elements_text(p_links) x where not exists(select 1 from public.sale_items i where i.tenant_id=p_tenant_id and i.sale_id=p_source_id and i.id=x::uuid);end if;
 elsif p_source_type='purchase' then
  select p.purchase_number,p.purchase_date,o.location_id into n,d,l from public.purchases p left join public.document_origins o on o.tenant_id=p.tenant_id and o.entity_type='purchase' and o.entity_id=p.id where p.tenant_id=p_tenant_id and p.id=p_source_id and p.status='posted';
  if n is not null then select count(*) into missing_count from jsonb_array_elements_text(p_links) x where not exists(select 1 from public.purchase_items i where i.tenant_id=p_tenant_id and i.purchase_id=p_source_id and i.id=x::uuid);end if;
 elsif p_source_type='sales_return' then
  select r.return_number,r.return_date,r.location_id into n,d,l from public.sales_returns r where r.tenant_id=p_tenant_id and r.id=p_source_id;
  if n is not null then select count(*) into missing_count from jsonb_array_elements_text(p_links) x where not exists(select 1 from public.sales_return_items i where i.sales_return_id=p_source_id and i.id=x::uuid);end if;
 elsif p_source_type='purchase_return' then
  select r.return_number,r.return_date,r.location_id into n,d,l from public.purchase_returns r where r.tenant_id=p_tenant_id and r.id=p_source_id;
  if n is not null then select count(*) into missing_count from jsonb_array_elements_text(p_links) x where not exists(select 1 from public.purchase_return_items i where i.purchase_return_id=p_source_id and i.id=x::uuid);end if;
 elsif p_source_type='purchase_invoice_v484' then
  select p.invoice_number,p.invoice_date,p.location_id into n,d,l from public.purchase_invoices_v484 p where p.tenant_id=p_tenant_id and p.id=p_source_id and p.status not in('draft','void');
  if n is not null then select count(*) into missing_count from jsonb_array_elements_text(p_links) x where not exists(select 1 from public.purchase_invoice_items_v484 i where i.purchase_invoice_id=p_source_id and i.id=x::uuid);end if;
 else raise exception 'Credit/debit note snapshot source is not enabled until dedicated v5.2 note source tables are introduced';end if;
 if n is null then raise exception 'GST snapshot source document not found or not finalized';end if;
 if n is distinct from trim(p_source_number) then raise exception 'GST snapshot source number mismatch';end if;
 if d is distinct from p_document_date then raise exception 'GST snapshot document date mismatch';end if;
 if l is null or l is distinct from p_location_id then raise exception 'GST snapshot source location mismatch or missing document origin';end if;
 if missing_count<>0 then raise exception 'One or more GST snapshot source line links do not belong to the source document';end if;
end$$;
revoke all on function private.gst_source_assert_v520(uuid,text,uuid,text,date,uuid,jsonb) from public,anon,authenticated;

create or replace function private.gst_snapshot_create_v520(p_tenant_id uuid,p_source_type text,p_source_id uuid,p_source_number text,p_location_id uuid,p_document_date date,p_quote jsonb,p_source_line_ids jsonb default '[]'::jsonb) returns uuid
language plpgsql security definer set search_path=public,private,pg_temp as $$
declare q jsonb:=coalesce(p_quote,'{}'::jsonb);totals jsonb;lines jsonb;line jsonb;links jsonb:=coalesce(p_source_line_ids,'[]'::jsonb);v_id uuid:=gen_random_uuid();v_kind text:=q->>'document_kind';v_class text:=q->>'document_class';v_direction text;v_registration_id uuid;v_mapped_registration_id uuid;i integer:=0;v_hash text;v_line_source uuid;
s_subtotal numeric:=0;s_discount numeric:=0;s_taxable numeric:=0;s_cgst numeric:=0;s_sgst numeric:=0;s_utgst numeric:=0;s_igst numeric:=0;s_cess numeric:=0;s_rcm_cgst numeric:=0;s_rcm_sgst numeric:=0;s_rcm_utgst numeric:=0;s_rcm_igst numeric:=0;s_rcm_cess numeric:=0;s_line_total numeric:=0;s_calc_round numeric:=0;
t_subtotal numeric;t_discount numeric;t_taxable numeric;t_cgst numeric;t_sgst numeric;t_utgst numeric;t_igst numeric;t_cess numeric;t_tax_collected numeric;t_rcm_cgst numeric;t_rcm_sgst numeric;t_rcm_utgst numeric;t_rcm_igst numeric;t_rcm_cess numeric;t_rcm_tax numeric;t_government_tax numeric;t_additional numeric;t_calc_round numeric;t_round numeric;t_grand numeric;v_interstate boolean;
begin
 if not private.erp_user_has_tenant_access(p_tenant_id) then raise exception 'Access denied';end if;
 if coalesce((q->>'ready_for_compliance')::boolean,false) is not true then raise exception 'GST quote is not compliance-ready and cannot be finalized';end if;
 if q->>'engine' not like 'gst_v520_document_%' then raise exception 'Unsupported GST engine payload';end if;
 if v_kind not in('sale','purchase') then raise exception 'Invalid GST quote document kind';end if;
 if v_class not in('tax_invoice','bill_of_supply','credit_note','debit_note') then raise exception 'Invalid GST quote document class';end if;
 if p_source_type not in('sale','purchase','sales_return','purchase_return','purchase_invoice_v484','credit_note','debit_note') then raise exception 'Unsupported GST snapshot source type';end if;
 if p_source_id is null or nullif(trim(coalesce(p_source_number,'')),'') is null or p_location_id is null or p_document_date is null then raise exception 'GST snapshot source id/number/date/location required';end if;
 if q->>'document_date' is not null and (q->>'document_date')::date is distinct from p_document_date then raise exception 'GST quote date and source date differ';end if;
 if exists(select 1 from public.gst_document_snapshots_v520 s where s.tenant_id=p_tenant_id and s.source_type=p_source_type and s.source_id=p_source_id) then raise exception 'GST snapshot already exists for source document';end if;
 if exists(select 1 from public.gst_legacy_document_markers_v520 m where m.tenant_id=p_tenant_id and m.source_type=p_source_type and m.source_id=p_source_id) then raise exception 'Source is marked legacy_unverified and cannot be replaced by an authoritative GST snapshot';end if;
 totals:=coalesce(q->'totals','{}'::jsonb);lines:=coalesce(q->'lines','[]'::jsonb);
 if jsonb_typeof(lines)<>'array' or jsonb_array_length(lines)=0 then raise exception 'GST snapshot requires quote lines';end if;
 if jsonb_typeof(links)<>'array' or jsonb_array_length(links)<>jsonb_array_length(lines) then raise exception 'Authoritative GST snapshot requires one source line id for every GST quote line';end if;
 if exists(select 1 from jsonb_array_elements_text(links) x where nullif(x,'') is null) then raise exception 'GST snapshot source line ids cannot be blank';end if;
 perform private.gst_source_assert_v520(p_tenant_id,p_source_type,p_source_id,trim(p_source_number),p_document_date,p_location_id,links);
 v_registration_id:=case when v_kind='sale' then nullif(q->>'supplier_registration_id','')::uuid else nullif(q->>'recipient_registration_id','')::uuid end;
 if v_registration_id is null then raise exception 'THQ GST registration is missing from compliance-ready quote';end if;
 select m.registration_id into v_mapped_registration_id from public.gst_location_registrations_v520 m where m.tenant_id=p_tenant_id and m.location_id=p_location_id and m.effective_from<=p_document_date and (m.effective_to is null or m.effective_to>=p_document_date) order by m.effective_from desc limit 1;
 if v_mapped_registration_id is null or v_mapped_registration_id is distinct from v_registration_id then raise exception 'GST quote registration does not match source location registration for document date';end if;
 for line in select value from jsonb_array_elements(lines) loop
  if coalesce((line->>'quantity')::numeric,0)<=0 then raise exception 'GST snapshot line quantity must be positive';end if;
  if abs(coalesce((line->>'tax_amount')::numeric,0)-(coalesce((line->>'cgst')::numeric,0)+coalesce((line->>'sgst')::numeric,0)+coalesce((line->>'utgst')::numeric,0)+coalesce((line->>'igst')::numeric,0)+coalesce((line->>'cess')::numeric,0)))>0.011 then raise exception 'GST snapshot line collected-tax components do not reconcile';end if;
  if abs(coalesce((line->>'rcm_tax_amount')::numeric,0)-(coalesce((line->>'rcm_cgst')::numeric,0)+coalesce((line->>'rcm_sgst')::numeric,0)+coalesce((line->>'rcm_utgst')::numeric,0)+coalesce((line->>'rcm_igst')::numeric,0)+coalesce((line->>'rcm_cess')::numeric,0)))>0.011 then raise exception 'GST snapshot line RCM components do not reconcile';end if;
  s_subtotal:=s_subtotal+round(coalesce((line->>'quantity')::numeric,0)*coalesce((line->>'unit_price')::numeric,0),4);s_discount:=s_discount+coalesce((line->>'discount')::numeric,0);s_taxable:=s_taxable+coalesce((line->>'taxable_value')::numeric,0);s_cgst:=s_cgst+coalesce((line->>'cgst')::numeric,0);s_sgst:=s_sgst+coalesce((line->>'sgst')::numeric,0);s_utgst:=s_utgst+coalesce((line->>'utgst')::numeric,0);s_igst:=s_igst+coalesce((line->>'igst')::numeric,0);s_cess:=s_cess+coalesce((line->>'cess')::numeric,0);s_rcm_cgst:=s_rcm_cgst+coalesce((line->>'rcm_cgst')::numeric,0);s_rcm_sgst:=s_rcm_sgst+coalesce((line->>'rcm_sgst')::numeric,0);s_rcm_utgst:=s_rcm_utgst+coalesce((line->>'rcm_utgst')::numeric,0);s_rcm_igst:=s_rcm_igst+coalesce((line->>'rcm_igst')::numeric,0);s_rcm_cess:=s_rcm_cess+coalesce((line->>'rcm_cess')::numeric,0);s_line_total:=s_line_total+coalesce((line->>'line_total')::numeric,0);s_calc_round:=s_calc_round+coalesce((line->>'calculation_rounding')::numeric,0);
 end loop;
 t_subtotal:=coalesce((totals->>'subtotal')::numeric,0);t_discount:=coalesce((totals->>'discount')::numeric,0);t_taxable:=coalesce((totals->>'taxable_value')::numeric,0);t_cgst:=coalesce((totals->>'cgst')::numeric,0);t_sgst:=coalesce((totals->>'sgst')::numeric,0);t_utgst:=coalesce((totals->>'utgst')::numeric,0);t_igst:=coalesce((totals->>'igst')::numeric,0);t_cess:=coalesce((totals->>'cess')::numeric,0);t_tax_collected:=coalesce((totals->>'tax_collected_total')::numeric,0);t_rcm_cgst:=coalesce((totals->>'rcm_cgst')::numeric,0);t_rcm_sgst:=coalesce((totals->>'rcm_sgst')::numeric,0);t_rcm_utgst:=coalesce((totals->>'rcm_utgst')::numeric,0);t_rcm_igst:=coalesce((totals->>'rcm_igst')::numeric,0);t_rcm_cess:=coalesce((totals->>'rcm_cess')::numeric,0);t_rcm_tax:=coalesce((totals->>'rcm_tax_payable_total')::numeric,0);t_government_tax:=coalesce((totals->>'government_tax_total')::numeric,0);t_additional:=coalesce((totals->>'additional_charges')::numeric,0);t_calc_round:=coalesce((totals->>'calculation_rounding')::numeric,0);t_round:=coalesce((totals->>'round_off')::numeric,0);t_grand:=coalesce((totals->>'grand_total')::numeric,0);
 if abs(round(s_subtotal,2)-round(t_subtotal,2))>0.011 or abs(round(s_discount,2)-round(t_discount,2))>0.011 or abs(round(s_taxable,2)-round(t_taxable,2))>0.011 then raise exception 'GST snapshot commercial totals do not reconcile to lines';end if;
 if abs(round(s_cgst,2)-round(t_cgst,2))>0.011 or abs(round(s_sgst,2)-round(t_sgst,2))>0.011 or abs(round(s_utgst,2)-round(t_utgst,2))>0.011 or abs(round(s_igst,2)-round(t_igst,2))>0.011 or abs(round(s_cess,2)-round(t_cess,2))>0.011 then raise exception 'GST snapshot collected-tax totals do not reconcile to lines';end if;
 if abs(round(s_rcm_cgst,2)-round(t_rcm_cgst,2))>0.011 or abs(round(s_rcm_sgst,2)-round(t_rcm_sgst,2))>0.011 or abs(round(s_rcm_utgst,2)-round(t_rcm_utgst,2))>0.011 or abs(round(s_rcm_igst,2)-round(t_rcm_igst,2))>0.011 or abs(round(s_rcm_cess,2)-round(t_rcm_cess,2))>0.011 then raise exception 'GST snapshot RCM totals do not reconcile to lines';end if;
 if abs(t_tax_collected-(t_cgst+t_sgst+t_utgst+t_igst+t_cess))>0.011 then raise exception 'GST snapshot header collected-tax total is inconsistent';end if;
 if abs(t_rcm_tax-(t_rcm_cgst+t_rcm_sgst+t_rcm_utgst+t_rcm_igst+t_rcm_cess))>0.011 then raise exception 'GST snapshot header RCM total is inconsistent';end if;
 if abs(t_government_tax-(t_tax_collected+t_rcm_tax))>0.011 then raise exception 'GST snapshot government-tax total is inconsistent';end if;
 if abs(round(s_line_total+t_additional+t_round,2)-round(t_grand,2))>0.011 then raise exception 'GST snapshot grand total does not reconcile to line totals/additional charges/round-off';end if;
 if abs(round(s_calc_round,2)-round(t_calc_round,2))>0.011 then raise exception 'GST snapshot calculation-rounding total does not reconcile to lines';end if;
 v_interstate:=nullif(q->>'interstate','')::boolean;
 if v_interstate is true and (t_cgst<>0 or t_sgst<>0 or t_utgst<>0 or t_rcm_cgst<>0 or t_rcm_sgst<>0 or t_rcm_utgst<>0) then raise exception 'Inter-state GST snapshot cannot contain CGST/SGST/UTGST components';end if;
 if v_interstate is false and (t_igst<>0 or t_rcm_igst<>0) then raise exception 'Intra-state GST snapshot cannot contain IGST components';end if;
 if t_sgst<>0 and t_utgst<>0 then raise exception 'GST snapshot cannot contain both SGST and UTGST';end if;if t_rcm_sgst<>0 and t_rcm_utgst<>0 then raise exception 'GST snapshot cannot contain both RCM SGST and RCM UTGST';end if;if v_class='bill_of_supply' and t_tax_collected<>0 then raise exception 'Bill of Supply cannot collect GST';end if;
 v_direction:=case when v_kind='sale' then 'outward' else 'inward' end;
 v_hash:=encode(extensions.digest(convert_to(jsonb_build_object('tenant_id',p_tenant_id,'source_type',p_source_type,'source_id',p_source_id,'source_number',trim(p_source_number),'document_date',p_document_date,'location_id',p_location_id,'source_line_ids',links,'quote',q)::text,'UTF8'),'sha256'),'hex');
 insert into public.gst_document_snapshots_v520(id,tenant_id,source_type,source_id,source_number,direction,document_kind,document_class,document_date,location_id,thq_registration_id,supplier_gstin,supplier_state_code,recipient_gstin,recipient_state_code,place_of_supply_code,supply_type,interstate,zero_rated,without_payment,deemed_export,composition_supplier,subtotal,discount_total,taxable_total,cgst_total,sgst_total,utgst_total,igst_total,cess_total,tax_collected_total,rcm_cgst_total,rcm_sgst_total,rcm_utgst_total,rcm_igst_total,rcm_cess_total,rcm_tax_payable_total,government_tax_total,additional_charges,calculation_rounding,round_off,grand_total,engine_version,quote_payload,snapshot_hash,created_by) values(v_id,p_tenant_id,p_source_type,p_source_id,trim(p_source_number),v_direction,v_kind,v_class,p_document_date,p_location_id,v_registration_id,nullif(q->>'supplier_gstin',''),nullif(q->>'supplier_state_code',''),nullif(q->>'recipient_gstin',''),nullif(q->>'recipient_state_code',''),nullif(q->>'place_of_supply_code',''),coalesce(q->>'supply_type','B2C'),v_interstate,coalesce((q->>'zero_rated')::boolean,false),coalesce((q->>'without_payment')::boolean,false),coalesce((q->>'deemed_export')::boolean,false),coalesce((q->>'composition_supplier')::boolean,false),t_subtotal,t_discount,t_taxable,t_cgst,t_sgst,t_utgst,t_igst,t_cess,t_tax_collected,t_rcm_cgst,t_rcm_sgst,t_rcm_utgst,t_rcm_igst,t_rcm_cess,t_rcm_tax,t_government_tax,t_additional,t_calc_round,t_round,t_grand,q->>'engine',q,v_hash,auth.uid());
 for line in select value from jsonb_array_elements(lines) loop i:=i+1;v_line_source:=(links->>(i-1))::uuid;insert into public.gst_document_line_snapshots_v520(tenant_id,snapshot_id,line_no,source_line_id,variant_id,product_name,variant_name,sku,supply_kind,hsn_sac,quantity,unit_price,discount_amount,taxability,tax_inclusive,reverse_charge,gst_rate,applied_gst_rate,cess_rate,applied_cess_rate,cess_per_unit,applied_cess_per_unit,taxable_value,cgst,sgst,utgst,igst,cess,tax_amount,rcm_cgst,rcm_sgst,rcm_utgst,rcm_igst,rcm_cess,rcm_tax_amount,calculation_rounding,line_total,profile_source,profile_status,line_payload) values(p_tenant_id,v_id,i,v_line_source,nullif(line->>'variant_id','')::uuid,line->>'product_name',line->>'variant_name',line->>'sku',line->>'supply_kind',line->>'hsn_sac',coalesce((line->>'quantity')::numeric,0),coalesce((line->>'unit_price')::numeric,0),coalesce((line->>'discount')::numeric,0),coalesce(line->>'taxability','taxable'),coalesce((line->>'tax_inclusive')::boolean,false),coalesce((line->>'reverse_charge')::boolean,false),coalesce((line->>'gst_rate')::numeric,0),coalesce((line->>'applied_gst_rate')::numeric,0),coalesce((line->>'cess_rate')::numeric,0),coalesce((line->>'applied_cess_rate')::numeric,0),coalesce((line->>'cess_per_unit')::numeric,0),coalesce((line->>'applied_cess_per_unit')::numeric,0),coalesce((line->>'taxable_value')::numeric,0),coalesce((line->>'cgst')::numeric,0),coalesce((line->>'sgst')::numeric,0),coalesce((line->>'utgst')::numeric,0),coalesce((line->>'igst')::numeric,0),coalesce((line->>'cess')::numeric,0),coalesce((line->>'tax_amount')::numeric,0),coalesce((line->>'rcm_cgst')::numeric,0),coalesce((line->>'rcm_sgst')::numeric,0),coalesce((line->>'rcm_utgst')::numeric,0),coalesce((line->>'rcm_igst')::numeric,0),coalesce((line->>'rcm_cess')::numeric,0),coalesce((line->>'rcm_tax_amount')::numeric,0),coalesce((line->>'calculation_rounding')::numeric,0),coalesce((line->>'line_total')::numeric,0),line->>'profile_source',line->>'profile_status',line);end loop;return v_id;
end$$;
revoke all on function private.gst_snapshot_create_v520(uuid,text,uuid,text,uuid,date,jsonb,jsonb) from public,anon,authenticated;grant execute on function private.gst_snapshot_create_v520(uuid,text,uuid,text,uuid,date,jsonb,jsonb) to service_role;
create or replace function public.gst_snapshot_get_v520(p_tenant_id uuid,p_source_type text,p_source_id uuid) returns jsonb language plpgsql stable security definer set search_path=public,private,pg_temp as $$declare v_lines jsonb;stored_hash text;calculated_hash text;links jsonb;q jsonb;s record;begin if not private.gst_v520_has_access(p_tenant_id,'gst_compliance.view') then raise exception 'GST compliance view permission required';end if;select x.* into s from public.gst_document_snapshots_v520 x where x.tenant_id=p_tenant_id and x.source_type=p_source_type and x.source_id=p_source_id;if not found then return null;end if;select coalesce(jsonb_agg(to_jsonb(l) order by l.line_no),'[]'::jsonb),coalesce(jsonb_agg(to_jsonb(l.source_line_id) order by l.line_no),'[]'::jsonb) into v_lines,links from public.gst_document_line_snapshots_v520 l where l.snapshot_id=s.id;q:=s.quote_payload;stored_hash:=s.snapshot_hash;calculated_hash:=encode(extensions.digest(convert_to(jsonb_build_object('tenant_id',s.tenant_id,'source_type',s.source_type,'source_id',s.source_id,'source_number',s.source_number,'document_date',s.document_date,'location_id',s.location_id,'source_line_ids',links,'quote',q)::text,'UTF8'),'sha256'),'hex');return to_jsonb(s)||jsonb_build_object('lines',v_lines,'hash_valid',stored_hash=calculated_hash);end$$;
revoke all on function public.gst_snapshot_get_v520(uuid,text,uuid) from public,anon;grant execute on function public.gst_snapshot_get_v520(uuid,text,uuid) to authenticated,service_role;
insert into public.thq_schema_releases(migration_no,schema_version,release_name,notes) values(225,'5.2.0-foundation','Authoritative GST Snapshot Contract','Binds compliance-ready GST engine output to actual finalized source documents and source lines, validates tax/RCM totals and stores a SHA-256 evidence fingerprint.') on conflict(migration_no) do update set schema_version=excluded.schema_version,release_name=excluded.release_name,notes=excluded.notes;
commit;