begin;
create or replace function public.accounting_register_v4(p_tenant_id uuid,p_register text,p_from date,p_to date,p_location_id uuid default null,p_query text default null)
returns table(entry_date date,reference text,party text,description text,debit numeric,credit numeric,location_code text,user_name text,source_type text,source_id uuid)
language plpgsql security definer set search_path=public,private,pg_temp as $$
declare q text:='%'||lower(trim(coalesce(p_query,'')))||'%';begin
  if not private.erp_user_has_tenant_access(p_tenant_id) then raise exception 'Access denied';end if;
  return query
  select j.entry_date,j.source_reference::text,coalesce(case when jl.party_type='customer' then c.name::text when jl.party_type='supplier' then s.name::text else '' end,'')::text,coalesce(jl.description::text,j.description::text,'')::text,jl.debit,jl.credit,coalesce(bl.location_code::text,'')::text,coalesce(ul.username::text,'')::text,j.source_type::text,j.source_id
  from public.journal_entries j join public.journal_lines jl on jl.journal_entry_id=j.id join public.accounting_accounts a on a.id=jl.account_id
  left join public.customers c on jl.party_type='customer' and c.id=jl.party_id left join public.suppliers s on jl.party_type='supplier' and s.id=jl.party_id left join public.business_locations bl on bl.id=j.location_id left join public.user_login_names ul on ul.user_id=j.created_by
  where j.tenant_id=p_tenant_id and j.status='posted' and j.entry_date between p_from and p_to and private.erp_document_scope_allowed(p_tenant_id,j.location_id,p_location_id,'view')
    and (p_register='all' or (p_register='sales' and j.source_type in('sale','sale_payment','sales_return')) or (p_register='purchases' and j.source_type in('purchase','purchase_payment','purchase_return')) or (p_register='cash' and a.system_key='cash') or (p_register='bank' and a.system_key in('bank','upi','card')) or (p_register='gst' and private.gst_v520_account_family(a.system_key) is not null) or (p_register='receivables' and a.system_key='accounts_receivable') or (p_register='payables' and a.system_key='accounts_payable') or (p_register='journal' and j.source_type='manual'))
    and (trim(coalesce(p_query,''))='' or lower(coalesce(j.source_reference::text,'')) like q or lower(coalesce(j.description::text,'')) like q or lower(coalesce(c.name::text,'')) like q or lower(coalesce(s.name::text,'')) like q or lower(coalesce(a.name::text,'')) like q
      or exists(select 1 from public.sales sx join public.sale_items six on six.sale_id=sx.id join public.product_variants pvx on pvx.id=six.variant_id join public.products prx on prx.id=pvx.product_id where sx.tenant_id=p_tenant_id and sx.id=case when j.source_type='sale' then j.source_id when j.source_type='sale_payment' then (select spx.sale_id from public.sale_payments spx where spx.id=j.source_id) when j.source_type='sales_return' then (select srx.sale_id from public.sales_returns srx where srx.id=j.source_id) else null end and (lower(prx.name::text) like q or lower(coalesce(pvx.sku::text,'')) like q or lower(coalesce(pvx.part_number::text,'')) like q))
      or exists(select 1 from public.purchases pxh join public.purchase_items pix on pix.purchase_id=pxh.id join public.product_variants pvx on pvx.id=pix.variant_id join public.products prx on prx.id=pvx.product_id where pxh.tenant_id=p_tenant_id and pxh.id=case when j.source_type='purchase' then j.source_id when j.source_type='purchase_payment' then (select ppx.purchase_id from public.purchase_payments ppx where ppx.id=j.source_id) when j.source_type='purchase_return' then (select prx2.purchase_id from public.purchase_returns prx2 where prx2.id=j.source_id) else null end and (lower(prx.name::text) like q or lower(coalesce(pvx.sku::text,'')) like q or lower(coalesce(pvx.part_number::text,'')) like q)) )
  order by j.entry_date desc,j.created_at desc;
end $$;
revoke all on function public.accounting_register_v4(uuid,text,date,date,uuid,text) from public,anon;
grant execute on function public.accounting_register_v4(uuid,text,date,date,uuid,text) to authenticated,service_role;

create or replace function public.finance_reconciliation_v500(p_tenant_id uuid) returns jsonb
language plpgsql stable security definer set search_path=public,private,pg_temp as $$
declare ar_op numeric:=0;ap_op numeric:=0;ar_gl numeric:=0;ap_gl numeric:=0;inv_op numeric:=0;inv_gl numeric:=0;cogs_op numeric:=0;cogs_gl numeric:=0;out_tax_op numeric:=0;out_tax_gl numeric:=0;in_tax_op numeric:=0;in_tax_gl numeric:=0;ar uuid;ap uuid;inv uuid;cogs uuid;unbalanced bigint:=0;zero_lines bigint:=0;duplicate_sources bigint:=0;missing_source bigint:=0;
begin
 perform private.v500_accounting_access(p_tenant_id,false);
 ar:=private.v4_account_id(p_tenant_id,'accounts_receivable');ap:=private.v4_account_id(p_tenant_id,'accounts_payable');inv:=private.v4_account_id(p_tenant_id,'inventory_asset');cogs:=private.v4_account_id(p_tenant_id,'cogs');
 select coalesce(sum(greatest(s.grand_total-coalesce(rt.x,0)-coalesce(py.x,0),0)),0) into ar_op from public.sales s left join(select sale_id,sum(grand_total)x from public.sales_returns where refund_status<>'waived' group by sale_id)rt on rt.sale_id=s.id left join(select sale_id,sum(amount)x from public.sale_payments group by sale_id)py on py.sale_id=s.id where s.tenant_id=p_tenant_id and coalesce(s.status,'') not in('void','cancelled');
 select coalesce(sum(x.balance),0) into ap_op from (select greatest(p.grand_total-coalesce(rt.x,0)-coalesce(py.x,0),0) balance from public.purchases p left join(select purchase_id,sum(grand_total)x from public.purchase_returns where credit_status<>'waived' group by purchase_id)rt on rt.purchase_id=p.id left join(select purchase_id,sum(amount)x from public.purchase_payments group by purchase_id)py on py.purchase_id=p.id where p.tenant_id=p_tenant_id and coalesce(p.status,'') not in('void','cancelled') union all select greatest(i.balance_due,0) from public.purchase_invoices_v484 i where i.tenant_id=p_tenant_id and i.status in('posted','part_paid'))x;
 select coalesce(sum(b.quantity*coalesce(nullif(b.average_cost,0),pv.cost_price,0)),0) into inv_op from public.location_stock_balances b join public.product_variants pv on pv.id=b.variant_id and pv.tenant_id=b.tenant_id where b.tenant_id=p_tenant_id;
 select coalesce(sum(si.cost_total),0)-coalesce((select sum(ri.quantity*coalesce(si2.unit_cost,0)) from public.sales_return_items ri join public.sales_returns r on r.id=ri.sales_return_id and r.tenant_id=p_tenant_id and r.refund_status<>'waived' join public.sale_items si2 on si2.id=ri.sale_item_id),0) into cogs_op from public.sale_items si join public.sales s on s.id=si.sale_id where s.tenant_id=p_tenant_id and coalesce(s.status,'') not in('void','cancelled');
 select coalesce(sum(tax_total),0)-coalesce((select sum(tax_total) from public.sales_returns where tenant_id=p_tenant_id and refund_status<>'waived'),0) into out_tax_op from public.sales where tenant_id=p_tenant_id and coalesce(status,'') not in('void','cancelled');
 select coalesce(sum(x.tax_total),0) into in_tax_op from (select tax_total from public.purchases where tenant_id=p_tenant_id and coalesce(status,'') not in('void','cancelled') union all select tax_total from public.purchase_invoices_v484 where tenant_id=p_tenant_id and status in('posted','part_paid','paid'))x;
 in_tax_op:=in_tax_op+coalesce((select sum(tax_amount) from public.expenses where tenant_id=p_tenant_id and status='posted'),0)-coalesce((select sum(tax_total) from public.purchase_returns where tenant_id=p_tenant_id and credit_status<>'waived'),0);
 select coalesce(sum(l.debit-l.credit),0) into ar_gl from public.journal_lines l join public.journal_entries j on j.id=l.journal_entry_id where j.tenant_id=p_tenant_id and j.status='posted' and l.account_id=ar;
 select coalesce(sum(l.credit-l.debit),0) into ap_gl from public.journal_lines l join public.journal_entries j on j.id=l.journal_entry_id where j.tenant_id=p_tenant_id and j.status='posted' and l.account_id=ap;
 select coalesce(sum(l.debit-l.credit),0) into inv_gl from public.journal_lines l join public.journal_entries j on j.id=l.journal_entry_id where j.tenant_id=p_tenant_id and j.status='posted' and l.account_id=inv;
 select coalesce(sum(l.debit-l.credit),0) into cogs_gl from public.journal_lines l join public.journal_entries j on j.id=l.journal_entry_id where j.tenant_id=p_tenant_id and j.status='posted' and l.account_id=cogs;
 select coalesce(sum(l.credit-l.debit),0) into out_tax_gl from public.journal_lines l join public.journal_entries j on j.id=l.journal_entry_id where j.tenant_id=p_tenant_id and j.status='posted' and l.account_id in(select account_id from private.gst_v520_account_ids(p_tenant_id,'output'));
 select coalesce(sum(l.debit-l.credit),0) into in_tax_gl from public.journal_lines l join public.journal_entries j on j.id=l.journal_entry_id where j.tenant_id=p_tenant_id and j.status='posted' and l.account_id in(select account_id from private.gst_v520_account_ids(p_tenant_id,'input_booked'));
 select count(*) into unbalanced from (select j.id from public.journal_entries j join public.journal_lines l on l.journal_entry_id=j.id where j.tenant_id=p_tenant_id and j.status='posted' group by j.id having round(sum(l.debit),2)<>round(sum(l.credit),2))q;
 select count(*) into zero_lines from public.journal_lines l join public.journal_entries j on j.id=l.journal_entry_id where j.tenant_id=p_tenant_id and j.status='posted' and round(l.debit,2)=0 and round(l.credit,2)=0;
 select count(*) into duplicate_sources from (select source_type,source_id from public.journal_entries where tenant_id=p_tenant_id and status='posted' and source_type is not null and source_id is not null group by source_type,source_id having count(*)>1)q;
 select count(*) into missing_source from (select s.id from public.sales s where s.tenant_id=p_tenant_id and coalesce(s.status,'') not in('void','cancelled') and not exists(select 1 from public.journal_entries j where j.tenant_id=p_tenant_id and j.source_type='sale' and j.source_id=s.id and j.status='posted') union all select p.id from public.purchases p where p.tenant_id=p_tenant_id and coalesce(p.status,'') not in('void','cancelled') and not exists(select 1 from public.journal_entries j where j.tenant_id=p_tenant_id and j.source_type='purchase' and j.source_id=p.id and j.status='posted') union all select r.id from public.sales_returns r where r.tenant_id=p_tenant_id and r.refund_status<>'waived' and not exists(select 1 from public.journal_entries j where j.tenant_id=p_tenant_id and j.source_type='sales_return' and j.source_id=r.id and j.status='posted') union all select r.id from public.purchase_returns r where r.tenant_id=p_tenant_id and r.credit_status<>'waived' and not exists(select 1 from public.journal_entries j where j.tenant_id=p_tenant_id and j.source_type='purchase_return' and j.source_id=r.id and j.status='posted'))q;
 return jsonb_build_object('ready',unbalanced=0 and zero_lines=0 and duplicate_sources=0 and missing_source=0 and abs(ar_op-ar_gl)<=0.05 and abs(ap_op-ap_gl)<=0.05 and abs(inv_op-inv_gl)<=0.05 and abs(cogs_op-cogs_gl)<=0.05 and abs(out_tax_op-out_tax_gl)<=0.05 and abs(in_tax_op-in_tax_gl)<=0.05,'accounts_receivable',jsonb_build_object('operational',round(ar_op,2),'general_ledger',round(ar_gl,2),'difference',round(ar_op-ar_gl,2),'reconciled',abs(ar_op-ar_gl)<=0.05),'accounts_payable',jsonb_build_object('operational',round(ap_op,2),'general_ledger',round(ap_gl,2),'difference',round(ap_op-ap_gl,2),'reconciled',abs(ap_op-ap_gl)<=0.05),'inventory',jsonb_build_object('operational_value',round(inv_op,2),'general_ledger',round(inv_gl,2),'difference',round(inv_op-inv_gl,2)),'cogs',jsonb_build_object('operational',round(cogs_op,2),'general_ledger',round(cogs_gl,2),'difference',round(cogs_op-cogs_gl,2)),'output_gst',jsonb_build_object('operational',round(out_tax_op,2),'general_ledger',round(out_tax_gl,2),'difference',round(out_tax_op-out_tax_gl,2)),'input_gst',jsonb_build_object('operational',round(in_tax_op,2),'general_ledger',round(in_tax_gl,2),'difference',round(in_tax_op-in_tax_gl,2)),'integrity',jsonb_build_object('unbalanced_posted_journals',unbalanced,'zero_value_posted_lines',zero_lines,'duplicate_source_journals',duplicate_sources,'missing_source_journals',missing_source),'checked_at',now());
end $$;
revoke all on function public.finance_reconciliation_v500(uuid) from public,anon;
grant execute on function public.finance_reconciliation_v500(uuid) to authenticated,service_role;

insert into public.thq_schema_releases(migration_no,schema_version,release_name,notes)
values(228,'5.2.0-foundation','GST-Aware Accounting Aggregation','Extends GST register and finance reconciliation so legacy generic GST postings and future component postings coexist without double counting. RCM payable and RCM input remain separate control families.')
on conflict(migration_no) do update set schema_version=excluded.schema_version,release_name=excluded.release_name,notes=excluded.notes;
commit;