-- THQ ERP v5.2 GST & Compliance
-- Migration 225: controlled immutable GST snapshot writer.
-- No sales/purchase/stock/accounting behavior changes in this migration.
begin;
create or replace function private.gst_sha256_jsonb_v520(p_payload jsonb) returns text language sql immutable set search_path=public,private,pg_temp as $$ select encode(extensions.digest(coalesce($1,'{}'::jsonb)::text,'sha256'),'hex') $$;
revoke all on function private.gst_sha256_jsonb_v520(jsonb) from public,anon,authenticated;
create or replace function private.gst_snapshot_create_v520(p_tenant_id uuid,p_source_type text,p_source_id uuid,p_source_number text,p_location_id uuid,p_quote jsonb,p_source_line_ids uuid[] default null,p_document_class_override text default null) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_source_type text:=lower(trim(coalesce(p_source_type,'')));v_kind text:=lower(coalesce(p_quote->>'document_kind',''));v_class text:=lower(coalesce(nullif(trim(coalesce(p_document_class_override,'')),''),p_quote->>'document_class',''));v_direction text;v_registration_id uuid;v_snapshot_id uuid;v_existing uuid;v_totals jsonb:=coalesce(p_quote->'totals','{}'::jsonb);v_ready boolean:=coalesce((p_quote->>'ready_for_compliance')::boolean,false);v_payload jsonb;v_hash text;v_line jsonb;v_line_no integer:=0;v_line_source_id uuid;v_quote_engine text:=coalesce(p_quote->>'engine','');v_quote_date date;v_source_number text:=trim(coalesce(p_source_number,''));v_source_doc jsonb;v_source_date date;v_source_total numeric;v_source_status text;v_source_location uuid;v_source_tenant uuid;v_source_number_actual text;
begin
if p_tenant_id is null or p_source_id is null or p_location_id is null then raise exception 'GST snapshot tenant, source and location are required';end if;
if v_source_type not in('sale','purchase','sales_return','purchase_return','purchase_invoice_v484','credit_note','debit_note') then raise exception 'Unsupported GST snapshot source type';end if;
if not v_ready then raise exception 'GST quote is not ready for compliance and cannot become authoritative evidence';end if;
if v_quote_engine not like 'gst_v520%' then raise exception 'GST quote was not produced by the v5.2 central GST engine';end if;
if jsonb_typeof(coalesce(p_quote->'lines','[]'::jsonb))<>'array' or jsonb_array_length(coalesce(p_quote->'lines','[]'::jsonb))=0 then raise exception 'GST authoritative snapshot requires at least one line';end if;
if v_kind not in('sale','purchase') then raise exception 'GST quote document kind is invalid';end if;
if v_class not in('tax_invoice','bill_of_supply','credit_note','debit_note') then raise exception 'GST document class is invalid';end if;
v_direction:=case when v_kind='sale' then 'outward' else 'inward' end;
if v_source_type in('sale','sales_return','credit_note','debit_note') and v_kind<>'sale' then raise exception 'Outward GST source must use a sale-oriented quote';end if;
if v_source_type in('purchase','purchase_return','purchase_invoice_v484') and v_kind<>'purchase' then raise exception 'Inward GST source must use a purchase-oriented quote';end if;
if v_source_type='sales_return' and p_document_class_override is null then v_class:='credit_note';end if;if v_source_type='purchase_return' and p_document_class_override is null then v_class:='credit_note';end if;
begin v_quote_date:=(p_quote->>'document_date')::date;exception when others then raise exception 'GST quote document date is invalid';end;
v_registration_id:=case when v_kind='sale' then nullif(p_quote->>'supplier_registration_id','')::uuid else nullif(p_quote->>'recipient_registration_id','')::uuid end;
if v_registration_id is null then raise exception 'THQ GST registration is missing from the central GST quote';end if;
if not exists(select 1 from public.gst_registrations_v520 r where r.id=v_registration_id and r.tenant_id=p_tenant_id) then raise exception 'GST registration does not belong to this tenant';end if;
if not exists(select 1 from public.business_locations l where l.id=p_location_id and l.tenant_id=p_tenant_id) then raise exception 'GST snapshot location does not belong to this tenant';end if;
if v_source_type='sale' then select s.tenant_id,s.sale_number,s.sale_date,s.grand_total,s.status,o.location_id,jsonb_build_object('id',s.id,'number',s.sale_number,'date',s.sale_date,'status',s.status,'subtotal',s.subtotal,'discount_total',s.discount_total,'taxable_total',s.taxable_total,'tax_total',s.tax_total,'additional_charges',s.additional_charges,'round_off',s.round_off,'grand_total',s.grand_total) into v_source_tenant,v_source_number_actual,v_source_date,v_source_total,v_source_status,v_source_location,v_source_doc from public.sales s left join public.document_origins o on o.tenant_id=s.tenant_id and o.entity_type='sale' and o.entity_id=s.id where s.id=p_source_id;
elsif v_source_type='purchase' then select p.tenant_id,p.purchase_number,p.purchase_date,p.grand_total,p.status,o.location_id,jsonb_build_object('id',p.id,'number',p.purchase_number,'date',p.purchase_date,'status',p.status,'subtotal',p.subtotal,'discount_total',p.discount_total,'taxable_total',p.taxable_total,'tax_total',p.tax_total,'additional_charges',p.additional_charges,'round_off',p.round_off,'grand_total',p.grand_total) into v_source_tenant,v_source_number_actual,v_source_date,v_source_total,v_source_status,v_source_location,v_source_doc from public.purchases p left join public.document_origins o on o.tenant_id=p.tenant_id and o.entity_type='purchase' and o.entity_id=p.id where p.id=p_source_id;
elsif v_source_type='sales_return' then select r.tenant_id,r.return_number,r.return_date,r.grand_total,'posted',r.location_id,jsonb_build_object('id',r.id,'number',r.return_number,'date',r.return_date,'subtotal',r.subtotal,'tax_total',r.tax_total,'grand_total',r.grand_total,'sale_id',r.sale_id) into v_source_tenant,v_source_number_actual,v_source_date,v_source_total,v_source_status,v_source_location,v_source_doc from public.sales_returns r where r.id=p_source_id;
elsif v_source_type='purchase_return' then select r.tenant_id,r.return_number,r.return_date,r.grand_total,'posted',r.location_id,jsonb_build_object('id',r.id,'number',r.return_number,'date',r.return_date,'subtotal',r.subtotal,'tax_total',r.tax_total,'grand_total',r.grand_total,'purchase_id',r.purchase_id) into v_source_tenant,v_source_number_actual,v_source_date,v_source_total,v_source_status,v_source_location,v_source_doc from public.purchase_returns r where r.id=p_source_id;
elsif v_source_type='purchase_invoice_v484' then select i.tenant_id,i.invoice_number,i.invoice_date,i.grand_total,i.status,i.location_id,jsonb_build_object('id',i.id,'number',i.invoice_number,'supplier_invoice_number',i.supplier_invoice_number,'date',i.invoice_date,'status',i.status,'subtotal',i.subtotal,'tax_total',i.tax_total,'additional_charges',i.additional_charges,'round_off',i.round_off,'grand_total',i.grand_total) into v_source_tenant,v_source_number_actual,v_source_date,v_source_total,v_source_status,v_source_location,v_source_doc from public.purchase_invoices_v484 i where i.id=p_source_id;
else raise exception 'Credit/debit-note authoritative binding will be enabled when normalized GST note source tables are introduced';end if;
if v_source_tenant is null then raise exception 'GST source document not found';end if;if v_source_tenant<>p_tenant_id then raise exception 'GST source document belongs to another tenant';end if;if v_source_number='' or v_source_number_actual is distinct from v_source_number then raise exception 'GST source document number does not match';end if;if v_source_date is distinct from v_quote_date then raise exception 'GST quote date does not match source document date';end if;if v_source_location is not null and v_source_location is distinct from p_location_id then raise exception 'GST quote location does not match source document origin';end if;if v_source_status in('cancelled','void','voided') then raise exception 'Cancelled/void source documents cannot create authoritative GST evidence';end if;if abs(coalesce(v_source_total,0)-coalesce((v_totals->>'grand_total')::numeric,0))>0.01 then raise exception 'GST quote total does not reconcile to source document total';end if;
v_payload:=jsonb_build_object('tenant_id',p_tenant_id,'source_type',v_source_type,'source_id',p_source_id,'source_number',v_source_number,'location_id',p_location_id,'document_class',v_class,'quote',p_quote,'source_line_ids',to_jsonb(p_source_line_ids));v_hash:=private.gst_sha256_jsonb_v520(v_payload);
select s.id into v_existing from public.gst_document_snapshots_v520 s where s.tenant_id=p_tenant_id and s.source_type=v_source_type and s.source_id=p_source_id;
if v_existing is not null then if exists(select 1 from public.gst_document_snapshots_v520 s where s.id=v_existing and s.snapshot_hash=v_hash) then return v_existing;end if;raise exception 'Authoritative GST evidence already exists for this source document with a different fingerprint';end if;
insert into public.gst_document_snapshots_v520(tenant_id,source_type,source_id,source_number,direction,document_kind,document_class,document_date,location_id,thq_registration_id,supplier_gstin,supplier_state_code,recipient_gstin,recipient_state_code,place_of_supply_code,supply_type,interstate,zero_rated,without_payment,deemed_export,composition_supplier,subtotal,discount_total,taxable_total,cgst_total,sgst_total,utgst_total,igst_total,cess_total,tax_collected_total,rcm_cgst_total,rcm_sgst_total,rcm_utgst_total,rcm_igst_total,rcm_cess_total,rcm_tax_payable_total,government_tax_total,additional_charges,calculation_rounding,round_off,grand_total,engine_version,quote_payload,snapshot_hash,created_by) values(p_tenant_id,v_source_type,p_source_id,v_source_number,v_direction,v_kind,v_class,v_quote_date,p_location_id,v_registration_id,nullif(p_quote->>'supplier_gstin',''),nullif(p_quote->>'supplier_state_code',''),nullif(p_quote->>'recipient_gstin',''),nullif(p_quote->>'recipient_state_code',''),nullif(p_quote->>'place_of_supply_code',''),coalesce(p_quote->>'supply_type',''),case when p_quote ? 'interstate' then (p_quote->>'interstate')::boolean else null end,coalesce((p_quote->>'zero_rated')::boolean,false),coalesce((p_quote->>'without_payment')::boolean,false),coalesce((p_quote->>'deemed_export')::boolean,false),coalesce((p_quote->>'composition_supplier')::boolean,false),coalesce((v_totals->>'subtotal')::numeric,0),coalesce((v_totals->>'discount')::numeric,0),coalesce((v_totals->>'taxable_value')::numeric,0),coalesce((v_totals->>'cgst')::numeric,0),coalesce((v_totals->>'sgst')::numeric,0),coalesce((v_totals->>'utgst')::numeric,0),coalesce((v_totals->>'igst')::numeric,0),coalesce((v_totals->>'cess')::numeric,0),coalesce((v_totals->>'tax_collected_total')::numeric,0),coalesce((v_totals->>'rcm_cgst')::numeric,0),coalesce((v_totals->>'rcm_sgst')::numeric,0),coalesce((v_totals->>'rcm_utgst')::numeric,0),coalesce((v_totals->>'rcm_igst')::numeric,0),coalesce((v_totals->>'rcm_cess')::numeric,0),coalesce((v_totals->>'rcm_tax_payable_total')::numeric,0),coalesce((v_totals->>'government_tax_total')::numeric,0),coalesce((v_totals->>'additional_charges')::numeric,0),coalesce((v_totals->>'calculation_rounding')::numeric,0),coalesce((v_totals->>'round_off')::numeric,0),coalesce((v_totals->>'grand_total')::numeric,0),v_quote_engine,p_quote,v_hash,auth.uid()) returning id into v_snapshot_id;
for v_line in select value from jsonb_array_elements(p_quote->'lines') loop v_line_no:=v_line_no+1;v_line_source_id:=case when p_source_line_ids is not null and array_length(p_source_line_ids,1)>=v_line_no then p_source_line_ids[v_line_no] else null end;insert into public.gst_document_line_snapshots_v520(tenant_id,snapshot_id,line_no,source_line_id,variant_id,product_name,variant_name,sku,supply_kind,hsn_sac,quantity,unit_price,discount_amount,taxability,tax_inclusive,reverse_charge,gst_rate,applied_gst_rate,cess_rate,applied_cess_rate,cess_per_unit,applied_cess_per_unit,taxable_value,cgst,sgst,utgst,igst,cess,tax_amount,rcm_cgst,rcm_sgst,rcm_utgst,rcm_igst,rcm_cess,rcm_tax_amount,calculation_rounding,line_total,profile_source,profile_status,line_payload) values(p_tenant_id,v_snapshot_id,v_line_no,v_line_source_id,nullif(v_line->>'variant_id','')::uuid,v_line->>'product_name',v_line->>'variant_name',v_line->>'sku',coalesce(v_line->>'supply_kind','goods'),nullif(v_line->>'hsn_sac',''),coalesce((v_line->>'quantity')::numeric,0),coalesce((v_line->>'unit_price')::numeric,0),coalesce((v_line->>'discount')::numeric,0),coalesce(v_line->>'taxability','taxable'),coalesce((v_line->>'tax_inclusive')::boolean,false),coalesce((v_line->>'reverse_charge')::boolean,false),coalesce((v_line->>'gst_rate')::numeric,0),coalesce((v_line->>'applied_gst_rate')::numeric,0),coalesce((v_line->>'cess_rate')::numeric,0),coalesce((v_line->>'applied_cess_rate')::numeric,0),coalesce((v_line->>'cess_per_unit')::numeric,0),coalesce((v_line->>'applied_cess_per_unit')::numeric,0),coalesce((v_line->>'taxable_value')::numeric,0),coalesce((v_line->>'cgst')::numeric,0),coalesce((v_line->>'sgst')::numeric,0),coalesce((v_line->>'utgst')::numeric,0),coalesce((v_line->>'igst')::numeric,0),coalesce((v_line->>'cess')::numeric,0),coalesce((v_line->>'tax_amount')::numeric,0),coalesce((v_line->>'rcm_cgst')::numeric,0),coalesce((v_line->>'rcm_sgst')::numeric,0),coalesce((v_line->>'rcm_utgst')::numeric,0),coalesce((v_line->>'rcm_igst')::numeric,0),coalesce((v_line->>'rcm_cess')::numeric,0),coalesce((v_line->>'rcm_tax_amount')::numeric,0),coalesce((v_line->>'calculation_rounding')::numeric,0),coalesce((v_line->>'line_total')::numeric,0),v_line->>'profile_source',v_line->>'profile_status',v_line);end loop;
if p_source_line_ids is not null and array_length(p_source_line_ids,1) is distinct from v_line_no then raise exception 'GST source-line mapping count does not match quote line count';end if;return v_snapshot_id;end $$;
revoke all on function private.gst_snapshot_create_v520(uuid,text,uuid,text,uuid,jsonb,uuid[],text) from public,anon,authenticated;
insert into public.thq_schema_releases(migration_no,schema_version,release_name,notes) values(225,'5.2.0-foundation','Controlled GST Evidence Writer','Adds the internal authoritative snapshot writer with source binding, deterministic SHA-256 fingerprinting, idempotency and source-line linkage. No transaction posting behavior changes.') on conflict(migration_no) do update set schema_version=excluded.schema_version,release_name=excluded.release_name,notes=excluded.notes;
commit;