begin;
create table if not exists public.gst_document_snapshots_v520 (
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,
 source_type text not null check(source_type in('sale','purchase','sales_return','purchase_return','purchase_invoice_v484','credit_note','debit_note')),
 source_id uuid not null,source_number text not null,direction text not null check(direction in('outward','inward')),
 document_kind text not null check(document_kind in('sale','purchase')),document_class text not null check(document_class in('tax_invoice','bill_of_supply','credit_note','debit_note')),
 document_date date not null,location_id uuid not null references public.business_locations(id),thq_registration_id uuid not null references public.gst_registrations_v520(id),
 supplier_gstin text,supplier_state_code text,recipient_gstin text,recipient_state_code text,place_of_supply_code text,supply_type text not null,interstate boolean,
 zero_rated boolean not null default false,without_payment boolean not null default false,deemed_export boolean not null default false,composition_supplier boolean not null default false,
 subtotal numeric(20,4) not null default 0,discount_total numeric(20,4) not null default 0,taxable_total numeric(20,4) not null default 0,
 cgst_total numeric(20,4) not null default 0,sgst_total numeric(20,4) not null default 0,utgst_total numeric(20,4) not null default 0,igst_total numeric(20,4) not null default 0,cess_total numeric(20,4) not null default 0,
 tax_collected_total numeric(20,4) not null default 0,rcm_cgst_total numeric(20,4) not null default 0,rcm_sgst_total numeric(20,4) not null default 0,rcm_utgst_total numeric(20,4) not null default 0,rcm_igst_total numeric(20,4) not null default 0,rcm_cess_total numeric(20,4) not null default 0,rcm_tax_payable_total numeric(20,4) not null default 0,government_tax_total numeric(20,4) not null default 0,
 additional_charges numeric(20,4) not null default 0,calculation_rounding numeric(20,4) not null default 0,round_off numeric(20,4) not null default 0,grand_total numeric(20,4) not null default 0,
 engine_version text not null,quote_payload jsonb not null,snapshot_hash text not null check(snapshot_hash ~ '^[0-9a-f]{64}$'),created_by uuid references auth.users(id),created_at timestamptz not null default now(),
 unique(tenant_id,source_type,source_id),check(abs(round_off)<=1.000001),check(not(sgst_total<>0 and utgst_total<>0)),check(not(rcm_sgst_total<>0 and rcm_utgst_total<>0))
);
create table if not exists public.gst_document_line_snapshots_v520 (
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,snapshot_id uuid not null references public.gst_document_snapshots_v520(id) on delete cascade,
 line_no integer not null check(line_no>0),source_line_id uuid,variant_id uuid references public.product_variants(id),product_name text,variant_name text,sku text,supply_kind text not null check(supply_kind in('goods','service')),hsn_sac text,
 quantity numeric(20,6) not null check(quantity>0),unit_price numeric(20,6) not null check(unit_price>=0),discount_amount numeric(20,4) not null default 0 check(discount_amount>=0),taxability text not null check(taxability in('taxable','nil_rated','exempt','non_gst')),tax_inclusive boolean not null default false,reverse_charge boolean not null default false,
 gst_rate numeric(9,4) not null default 0 check(gst_rate between 0 and 100),applied_gst_rate numeric(9,4) not null default 0 check(applied_gst_rate between 0 and 100),cess_rate numeric(9,4) not null default 0 check(cess_rate between 0 and 100),applied_cess_rate numeric(9,4) not null default 0 check(applied_cess_rate between 0 and 100),cess_per_unit numeric(20,6) not null default 0 check(cess_per_unit>=0),applied_cess_per_unit numeric(20,6) not null default 0 check(applied_cess_per_unit>=0),taxable_value numeric(20,4) not null default 0 check(taxable_value>=0),
 cgst numeric(20,4) not null default 0 check(cgst>=0),sgst numeric(20,4) not null default 0 check(sgst>=0),utgst numeric(20,4) not null default 0 check(utgst>=0),igst numeric(20,4) not null default 0 check(igst>=0),cess numeric(20,4) not null default 0 check(cess>=0),tax_amount numeric(20,4) not null default 0 check(tax_amount>=0),
 rcm_cgst numeric(20,4) not null default 0 check(rcm_cgst>=0),rcm_sgst numeric(20,4) not null default 0 check(rcm_sgst>=0),rcm_utgst numeric(20,4) not null default 0 check(rcm_utgst>=0),rcm_igst numeric(20,4) not null default 0 check(rcm_igst>=0),rcm_cess numeric(20,4) not null default 0 check(rcm_cess>=0),rcm_tax_amount numeric(20,4) not null default 0 check(rcm_tax_amount>=0),
 calculation_rounding numeric(20,4) not null default 0,line_total numeric(20,4) not null default 0 check(line_total>=0),profile_source text,profile_status text,line_payload jsonb not null,created_at timestamptz not null default now(),
 unique(snapshot_id,line_no),unique(snapshot_id,source_line_id),check(not(sgst<>0 and utgst<>0)),check(not(rcm_sgst<>0 and rcm_utgst<>0))
);
create table if not exists public.gst_legacy_document_markers_v520 (
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,source_type text not null check(source_type in('sale','purchase','sales_return','purchase_return','purchase_invoice_v484')),source_id uuid not null,source_number text not null,document_date date not null,location_id uuid references public.business_locations(id),legacy_taxable_total numeric(20,4),legacy_tax_total numeric(20,4) not null default 0,legacy_grand_total numeric(20,4) not null default 0,verification_status text not null default 'legacy_unverified' check(verification_status='legacy_unverified'),note text not null default 'Pre-v5.2 generic tax transaction. CGST/SGST/UTGST/IGST/Cess/RCM split was not stored and has not been fabricated.',source_hash text not null check(source_hash ~ '^[0-9a-f]{64}$'),marked_at timestamptz not null default now(),unique(tenant_id,source_type,source_id)
);
create index if not exists idx_gst_doc_snapshots_period on public.gst_document_snapshots_v520(tenant_id,document_date,direction);
create index if not exists idx_gst_doc_snapshots_registration on public.gst_document_snapshots_v520(tenant_id,thq_registration_id,document_date);
create index if not exists idx_gst_doc_lines_hsn on public.gst_document_line_snapshots_v520(tenant_id,hsn_sac);
create index if not exists idx_gst_legacy_period on public.gst_legacy_document_markers_v520(tenant_id,document_date,source_type);
alter table public.gst_document_snapshots_v520 enable row level security;alter table public.gst_document_line_snapshots_v520 enable row level security;alter table public.gst_legacy_document_markers_v520 enable row level security;
revoke all on public.gst_document_snapshots_v520,public.gst_document_line_snapshots_v520,public.gst_legacy_document_markers_v520 from public,anon,authenticated;
grant select,insert on public.gst_document_snapshots_v520,public.gst_document_line_snapshots_v520,public.gst_legacy_document_markers_v520 to service_role;
create or replace function private.gst_snapshot_immutable_v520() returns trigger language plpgsql set search_path=public,private,pg_temp as $$begin raise exception 'GST evidence is immutable. Use a linked return, credit/debit note or amendment instead of editing/deleting the original GST evidence';end$$;
revoke all on function private.gst_snapshot_immutable_v520() from public,anon,authenticated;
drop trigger if exists trg_gst_document_snapshot_immutable_v520 on public.gst_document_snapshots_v520;create trigger trg_gst_document_snapshot_immutable_v520 before update or delete on public.gst_document_snapshots_v520 for each row execute function private.gst_snapshot_immutable_v520();
drop trigger if exists trg_gst_document_line_snapshot_immutable_v520 on public.gst_document_line_snapshots_v520;create trigger trg_gst_document_line_snapshot_immutable_v520 before update or delete on public.gst_document_line_snapshots_v520 for each row execute function private.gst_snapshot_immutable_v520();
drop trigger if exists trg_gst_legacy_marker_immutable_v520 on public.gst_legacy_document_markers_v520;create trigger trg_gst_legacy_marker_immutable_v520 before update or delete on public.gst_legacy_document_markers_v520 for each row execute function private.gst_snapshot_immutable_v520();
insert into public.thq_schema_releases(migration_no,schema_version,release_name,notes) values(224,'5.2.0-foundation','Immutable GST Evidence Schema','Creates immutable authoritative GST header/line snapshot storage and legacy-unverified marker storage. No historical tax components are inferred.') on conflict(migration_no) do update set schema_version=excluded.schema_version,release_name=excluded.release_name,notes=excluded.notes;
commit;