-- THQ ERP v5.2 GST & Compliance
-- Migration 226: immutable legacy-unverified evidence markers and reader.
begin;
create or replace function private.gst_legacy_mark_source_v520(p_tenant_id uuid,p_source_type text,p_source_id uuid) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_type text:=lower(trim(coalesce(p_source_type,'')));v_number text;v_date date;v_location uuid;v_taxable numeric;v_tax numeric;v_grand numeric;v_doc jsonb;v_lines jsonb;v_id uuid;v_hash text;
begin if p_tenant_id is null or p_source_id is null then raise exception 'Legacy GST marker tenant/source required';end if;if exists(select 1 from public.gst_document_snapshots_v520 s where s.tenant_id=p_tenant_id and s.source_type=v_type and s.source_id=p_source_id) then raise exception 'Source already has authoritative GST evidence';end if;
if v_type='sale' then select s.sale_number,s.sale_date,o.location_id,s.taxable_total,s.tax_total,s.grand_total,to_jsonb(s),coalesce((select jsonb_agg(to_jsonb(i) order by i.id) from public.sale_items i where i.tenant_id=s.tenant_id and i.sale_id=s.id),'[]'::jsonb) into v_number,v_date,v_location,v_taxable,v_tax,v_grand,v_doc,v_lines from public.sales s left join public.document_origins o on o.tenant_id=s.tenant_id and o.entity_type='sale' and o.entity_id=s.id where s.id=p_source_id and s.tenant_id=p_tenant_id;
elsif v_type='purchase' then select p.purchase_number,p.purchase_date,o.location_id,p.taxable_total,p.tax_total,p.grand_total,to_jsonb(p),coalesce((select jsonb_agg(to_jsonb(i) order by i.id) from public.purchase_items i where i.tenant_id=p.tenant_id and i.purchase_id=p.id),'[]'::jsonb) into v_number,v_date,v_location,v_taxable,v_tax,v_grand,v_doc,v_lines from public.purchases p left join public.document_origins o on o.tenant_id=p.tenant_id and o.entity_type='purchase' and o.entity_id=p.id where p.id=p_source_id and p.tenant_id=p_tenant_id;
elsif v_type='sales_return' then select r.return_number,r.return_date,r.location_id,r.subtotal,r.tax_total,r.grand_total,to_jsonb(r),coalesce((select jsonb_agg(to_jsonb(i) order by i.id) from public.sales_return_items i where i.sales_return_id=r.id),'[]'::jsonb) into v_number,v_date,v_location,v_taxable,v_tax,v_grand,v_doc,v_lines from public.sales_returns r where r.id=p_source_id and r.tenant_id=p_tenant_id;
elsif v_type='purchase_return' then select r.return_number,r.return_date,r.location_id,r.subtotal,r.tax_total,r.grand_total,to_jsonb(r),coalesce((select jsonb_agg(to_jsonb(i) order by i.id) from public.purchase_return_items i where i.purchase_return_id=r.id),'[]'::jsonb) into v_number,v_date,v_location,v_taxable,v_tax,v_grand,v_doc,v_lines from public.purchase_returns r where r.id=p_source_id and r.tenant_id=p_tenant_id;
elsif v_type='purchase_invoice_v484' then select i.invoice_number,i.invoice_date,i.location_id,i.subtotal,i.tax_total,i.grand_total,to_jsonb(i),coalesce((select jsonb_agg(to_jsonb(x) order by x.id) from public.purchase_invoice_items_v484 x where x.purchase_invoice_id=i.id),'[]'::jsonb) into v_number,v_date,v_location,v_taxable,v_tax,v_grand,v_doc,v_lines from public.purchase_invoices_v484 i where i.id=p_source_id and i.tenant_id=p_tenant_id;
else raise exception 'Unsupported legacy GST source type';end if;
if v_number is null then raise exception 'Legacy GST source document not found';end if;v_hash:=private.gst_sha256_jsonb_v520(jsonb_build_object('source_type',v_type,'document',v_doc,'lines',v_lines));insert into public.gst_legacy_document_markers_v520(tenant_id,source_type,source_id,source_number,document_date,location_id,legacy_taxable_total,legacy_tax_total,legacy_grand_total,source_hash) values(p_tenant_id,v_type,p_source_id,v_number,v_date,v_location,v_taxable,coalesce(v_tax,0),coalesce(v_grand,0),v_hash) on conflict(tenant_id,source_type,source_id) do nothing returning id into v_id;if v_id is null then select id into v_id from public.gst_legacy_document_markers_v520 where tenant_id=p_tenant_id and source_type=v_type and source_id=p_source_id;end if;return v_id;end $$;
revoke all on function private.gst_legacy_mark_source_v520(uuid,text,uuid) from public,anon,authenticated;
create or replace function private.gst_legacy_backfill_v520(p_tenant_id uuid) returns jsonb language plpgsql security definer set search_path=public,private,pg_temp as $$declare r record;v_sales int:=0;v_purchases int:=0;v_sr int:=0;v_pr int:=0;v_pi int:=0;begin for r in select id from public.sales where tenant_id=p_tenant_id loop perform private.gst_legacy_mark_source_v520(p_tenant_id,'sale',r.id);v_sales:=v_sales+1;end loop;for r in select id from public.purchases where tenant_id=p_tenant_id loop perform private.gst_legacy_mark_source_v520(p_tenant_id,'purchase',r.id);v_purchases:=v_purchases+1;end loop;for r in select id from public.sales_returns where tenant_id=p_tenant_id loop perform private.gst_legacy_mark_source_v520(p_tenant_id,'sales_return',r.id);v_sr:=v_sr+1;end loop;for r in select id from public.purchase_returns where tenant_id=p_tenant_id loop perform private.gst_legacy_mark_source_v520(p_tenant_id,'purchase_return',r.id);v_pr:=v_pr+1;end loop;for r in select id from public.purchase_invoices_v484 where tenant_id=p_tenant_id loop perform private.gst_legacy_mark_source_v520(p_tenant_id,'purchase_invoice_v484',r.id);v_pi:=v_pi+1;end loop;return jsonb_build_object('sales',v_sales,'purchases',v_purchases,'sales_returns',v_sr,'purchase_returns',v_pr,'purchase_invoices_v484',v_pi);end $$;
revoke all on function private.gst_legacy_backfill_v520(uuid) from public,anon,authenticated;
create or replace function public.gst_document_evidence_v520(p_tenant_id uuid,p_source_type text,p_source_id uuid) returns jsonb language plpgsql stable security definer set search_path=public,private,pg_temp as $$declare v jsonb;begin if not private.gst_v520_has_access(p_tenant_id,'gst_compliance.view') then raise exception 'GST compliance view permission required';end if;select jsonb_build_object('evidence_status','authoritative','snapshot',to_jsonb(s),'lines',coalesce((select jsonb_agg(to_jsonb(l) order by l.line_no) from public.gst_document_line_snapshots_v520 l where l.snapshot_id=s.id),'[]'::jsonb)) into v from public.gst_document_snapshots_v520 s where s.tenant_id=p_tenant_id and s.source_type=lower(trim(p_source_type)) and s.source_id=p_source_id;if v is not null then return v;end if;select jsonb_build_object('evidence_status','legacy_unverified','marker',to_jsonb(m)) into v from public.gst_legacy_document_markers_v520 m where m.tenant_id=p_tenant_id and m.source_type=lower(trim(p_source_type)) and m.source_id=p_source_id;return coalesce(v,jsonb_build_object('evidence_status','not_snapshotted'));end $$;
revoke all on function public.gst_document_evidence_v520(uuid,text,uuid) from public,anon;grant execute on function public.gst_document_evidence_v520(uuid,text,uuid) to authenticated,service_role;
insert into public.thq_schema_releases(migration_no,schema_version,release_name,notes) values(226,'5.2.0-foundation','Legacy GST Evidence Markers','Adds immutable legacy-unverified markers/backfill helpers and the permissioned evidence reader. Historical CGST/SGST/UTGST/IGST/Cess/RCM components are never fabricated.') on conflict(migration_no) do update set schema_version=excluded.schema_version,release_name=excluded.release_name,notes=excluded.notes;
commit;