insert into public.permissions(key,module_key,name,description) values('gst_compliance.calculate','gst_compliance','Calculate GST','Use the centralized GST engine while creating operational Sales/Purchase documents. Does not grant GST setup, reconciliation, return submission, IRN cancellation, or period-lock rights.') on conflict(key) do update set module_key=excluded.module_key,name=excluded.name,description=excluded.description;

create or replace function private.gst_grant_calculate_operational_roles_v520(p_tenant_id uuid) returns integer language plpgsql security definer set search_path=public,private,pg_temp as $$ declare v_count integer:=0;begin if not exists(select 1 from public.tenant_modules tm where tm.tenant_id=p_tenant_id and tm.module_key='gst_compliance' and tm.enabled) then return 0;end if;with ins as (insert into public.role_permissions(role_id,permission_key) select r.id,'gst_compliance.calculate' from public.roles r where r.tenant_id=p_tenant_id and r.key in('owner','manager','cashier','salesperson','store_keeper','accountant') on conflict do nothing returning 1) select count(*) into v_count from ins;return v_count;end $$;
create or replace function private.gst_role_calculate_permission_after_insert_v520() returns trigger language plpgsql security definer set search_path=public,private,pg_temp as $$ begin if new.key in('owner','manager','cashier','salesperson','store_keeper','accountant') then perform private.gst_grant_calculate_operational_roles_v520(new.tenant_id);end if;return new;end $$;
create or replace function private.gst_module_calculate_permission_after_enable_v520() returns trigger language plpgsql security definer set search_path=public,private,pg_temp as $$ begin if new.module_key='gst_compliance' and new.enabled then perform private.gst_grant_calculate_operational_roles_v520(new.tenant_id);end if;return new;end $$;
drop trigger if exists trg_gst_role_calculate_permission_v520 on public.roles;
create trigger trg_gst_role_calculate_permission_v520 after insert on public.roles for each row execute function private.gst_role_calculate_permission_after_insert_v520();
drop trigger if exists trg_gst_module_calculate_permission_v520 on public.tenant_modules;
create trigger trg_gst_module_calculate_permission_v520 after insert or update of enabled on public.tenant_modules for each row execute function private.gst_module_calculate_permission_after_enable_v520();
do $$ declare r record;begin for r in select id from public.tenants loop perform private.gst_grant_calculate_operational_roles_v520(r.id);end loop;end $$;
do $$ declare v_oid oid;v_def text;v_old text:='if not private.gst_v520_has_access(p_tenant_id,''gst_compliance.view'') then raise exception ''GST compliance view permission required'';end if;';v_new text:='if not (private.gst_v520_has_access(p_tenant_id,''gst_compliance.calculate'') or private.gst_v520_has_access(p_tenant_id,''gst_compliance.view'')) then raise exception ''GST calculation permission required'';end if;';begin select p.oid into v_oid from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='gst_document_quote_v520' and pg_get_function_identity_arguments(p.oid)='p_tenant_id uuid, p_document_kind text, p_location_id uuid, p_party_id uuid, p_document_date date, p_supply_type text, p_place_of_supply_code text, p_items jsonb, p_additional_charges numeric, p_round_off numeric';if v_oid is null then raise exception 'GST document quote function not found';end if;v_def:=pg_get_functiondef(v_oid);if position('gst_compliance.calculate' in v_def)=0 then if position(v_old in v_def)=0 then raise exception 'GST quote access guard did not match expected foundation definition';end if;v_def:=replace(v_def,v_old,v_new);execute v_def;end if;end $$;
revoke all on function private.gst_grant_calculate_operational_roles_v520(uuid) from public,anon,authenticated;
revoke all on function private.gst_role_calculate_permission_after_insert_v520() from public,anon,authenticated;
revoke all on function private.gst_module_calculate_permission_after_enable_v520() from public,anon,authenticated;
grant execute on function private.gst_grant_calculate_operational_roles_v520(uuid) to service_role;
insert into public.thq_schema_releases(migration_no,schema_version,release_name,notes) values(237,'5.2.0-foundation','GST Operational Calculation Permission','Adds least-privilege gst_compliance.calculate for operational roles, seeds current roles, auto-grants it for future roles/module enablement, and allows only the central GST quote engine to accept calculate-or-view access. Higher GST workspace/configuration/reconciliation/submission/cancellation permissions remain separate.') on conflict(migration_no) do update set schema_version=excluded.schema_version,release_name=excluded.release_name,notes=excluded.notes;