begin;
create or replace function private.gst_legacy_source_payload_v520(p_tenant_id uuid,p_source_type text,p_source_id uuid) returns jsonb language plpgsql stable security definer set search_path=public,private,pg_temp as $$declare v jsonb;begin case p_source_type
when 'sale' then select jsonb_build_object('source_type','sale','id',s.id,'number',s.sale_number,'date',s.sale_date,'location_id',o.location_id,'taxable_total',s.taxable_total,'tax_total',s.tax_total,'grand_total',s.grand_total,'lines',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'variant_id',i.variant_id,'quantity',i.quantity,'unit_price',i.unit_price,'discount',i.discount_amount,'tax_rate',i.tax_rate,'taxable',i.taxable_amount,'tax',i.tax_amount,'line_total',i.line_total) order by i.id) from public.sale_items i where i.tenant_id=s.tenant_id and i.sale_id=s.id),'[]'::jsonb)) into v from public.sales s left join public.document_origins o on o.tenant_id=s.tenant_id and o.entity_type='sale' and o.entity_id=s.id where s.tenant_id=p_tenant_id and s.id=p_source_id and s.status='posted';
when 'purchase' then select jsonb_build_object('source_type','purchase','id',p.id,'number',p.purchase_number,'date',p.purchase_date,'location_id',o.location_id,'taxable_total',p.taxable_total,'tax_total',p.tax_total,'grand_total',p.grand_total,'lines',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'variant_id',i.variant_id,'quantity',i.quantity,'unit_cost',i.unit_cost,'discount',i.discount_amount,'tax_rate',i.tax_rate,'taxable',i.taxable_amount,'tax',i.tax_amount,'line_total',i.line_total) order by i.id) from public.purchase_items i where i.tenant_id=p.tenant_id and i.purchase_id=p.id),'[]'::jsonb)) into v from public.purchases p left join public.document_origins o on o.tenant_id=p.tenant_id and o.entity_type='purchase' and o.entity_id=p.id where p.tenant_id=p_tenant_id and p.id=p_source_id and p.status='posted';
when 'sales_return' then select jsonb_build_object('source_type','sales_return','id',r.id,'number',r.return_number,'date',r.return_date,'location_id',r.location_id,'tax_total',r.tax_total,'grand_total',r.grand_total,'lines',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'sale_item_id',i.sale_item_id,'variant_id',i.variant_id,'quantity',i.quantity,'unit_price',i.unit_price,'discount',i.discount_amount,'tax_rate',i.tax_rate,'line_total',i.line_total) order by i.id) from public.sales_return_items i where i.sales_return_id=r.id),'[]'::jsonb)) into v from public.sales_returns r where r.tenant_id=p_tenant_id and r.id=p_source_id;
when 'purchase_return' then select jsonb_build_object('source_type','purchase_return','id',r.id,'number',r.return_number,'date',r.return_date,'location_id',r.location_id,'tax_total',r.tax_total,'grand_total',r.grand_total,'lines',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'purchase_item_id',i.purchase_item_id,'variant_id',i.variant_id,'quantity',i.quantity,'unit_cost',i.unit_cost,'discount',i.discount_amount,'tax_rate',i.tax_rate,'line_total',i.line_total) order by i.id) from public.purchase_return_items i where i.purchase_return_id=r.id),'[]'::jsonb)) into v from public.purchase_returns r where r.tenant_id=p_tenant_id and r.id=p_source_id;
when 'purchase_invoice_v484' then select jsonb_build_object('source_type','purchase_invoice_v484','id',p.id,'number',p.invoice_number,'date',p.invoice_date,'location_id',p.location_id,'subtotal',p.subtotal,'tax_total',p.tax_total,'grand_total',p.grand_total,'lines',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'variant_id',i.variant_id,'quantity',i.quantity,'unit_cost',i.unit_cost,'tax_rate',i.tax_rate,'subtotal',i.line_subtotal,'tax',i.tax_amount,'line_total',i.line_total) order by i.id) from public.purchase_invoice_items_v484 i where i.purchase_invoice_id=p.id),'[]'::jsonb)) into v from public.purchase_invoices_v484 p where p.tenant_id=p_tenant_id and p.id=p_source_id and p.status not in('draft','void');
else raise exception 'Unsupported legacy GST source type';end case;return v;end$$;
revoke all on function private.gst_legacy_source_payload_v520(uuid,text,uuid) from public,anon,authenticated;
create or replace function private.gst_legacy_marker_sync_v520(p_tenant_id uuid default null) returns jsonb language plpgsql security definer set search_path=public,private,pg_temp as $$declare row_rec record;p jsonb;inserted_count integer:=0;begin for row_rec in
select 'sale'::text source_type,s.tenant_id,s.id source_id,s.sale_number source_number,s.sale_date document_date,o.location_id,s.taxable_total legacy_taxable_total,s.tax_total legacy_tax_total,s.grand_total legacy_grand_total from public.sales s left join public.document_origins o on o.tenant_id=s.tenant_id and o.entity_type='sale' and o.entity_id=s.id where s.status='posted' and (p_tenant_id is null or s.tenant_id=p_tenant_id)
union all select 'purchase',p.tenant_id,p.id,p.purchase_number,p.purchase_date,o.location_id,p.taxable_total,p.tax_total,p.grand_total from public.purchases p left join public.document_origins o on o.tenant_id=p.tenant_id and o.entity_type='purchase' and o.entity_id=p.id where p.status='posted' and (p_tenant_id is null or p.tenant_id=p_tenant_id)
union all select 'sales_return',sr.tenant_id,sr.id,sr.return_number,sr.return_date,sr.location_id,null::numeric,sr.tax_total,sr.grand_total from public.sales_returns sr where p_tenant_id is null or sr.tenant_id=p_tenant_id
union all select 'purchase_return',pr.tenant_id,pr.id,pr.return_number,pr.return_date,pr.location_id,null::numeric,pr.tax_total,pr.grand_total from public.purchase_returns pr where p_tenant_id is null or pr.tenant_id=p_tenant_id
union all select 'purchase_invoice_v484',i.tenant_id,i.id,i.invoice_number,i.invoice_date,i.location_id,i.subtotal,i.tax_total,i.grand_total from public.purchase_invoices_v484 i where i.status not in('draft','void') and (p_tenant_id is null or i.tenant_id=p_tenant_id)
loop if exists(select 1 from public.gst_document_snapshots_v520 s where s.tenant_id=row_rec.tenant_id and s.source_type=row_rec.source_type and s.source_id=row_rec.source_id) then continue;end if;if exists(select 1 from public.gst_legacy_document_markers_v520 m where m.tenant_id=row_rec.tenant_id and m.source_type=row_rec.source_type and m.source_id=row_rec.source_id) then continue;end if;p:=private.gst_legacy_source_payload_v520(row_rec.tenant_id,row_rec.source_type,row_rec.source_id);if p is null then continue;end if;insert into public.gst_legacy_document_markers_v520(tenant_id,source_type,source_id,source_number,document_date,location_id,legacy_taxable_total,legacy_tax_total,legacy_grand_total,source_hash) values(row_rec.tenant_id,row_rec.source_type,row_rec.source_id,row_rec.source_number,row_rec.document_date,row_rec.location_id,row_rec.legacy_taxable_total,row_rec.legacy_tax_total,row_rec.legacy_grand_total,encode(extensions.digest(convert_to(p::text,'UTF8'),'sha256'),'hex'));inserted_count:=inserted_count+1;end loop;return jsonb_build_object('success',true,'inserted',inserted_count);end$$;
revoke all on function private.gst_legacy_marker_sync_v520(uuid) from public,anon,authenticated;grant execute on function private.gst_legacy_marker_sync_v520(uuid) to service_role;
create or replace function public.gst_legacy_marker_get_v520(p_tenant_id uuid,p_source_type text,p_source_id uuid) returns jsonb language plpgsql stable security definer set search_path=public,private,pg_temp as $$declare m public.gst_legacy_document_markers_v520%rowtype;p jsonb;current_hash text;begin if not private.gst_v520_has_access(p_tenant_id,'gst_compliance.view') then raise exception 'GST compliance view permission required';end if;select * into m from public.gst_legacy_document_markers_v520 x where x.tenant_id=p_tenant_id and x.source_type=p_source_type and x.source_id=p_source_id;if not found then return null;end if;p:=private.gst_legacy_source_payload_v520(p_tenant_id,p_source_type,p_source_id);current_hash:=case when p is null then null else encode(extensions.digest(convert_to(p::text,'UTF8'),'sha256'),'hex') end;return to_jsonb(m)||jsonb_build_object('source_still_exists',p is not null,'source_hash_valid',current_hash is not null and current_hash=m.source_hash);end$$;
revoke all on function public.gst_legacy_marker_get_v520(uuid,text,uuid) from public,anon;grant execute on function public.gst_legacy_marker_get_v520(uuid,text,uuid) to authenticated,service_role;
create or replace function public.gst_snapshot_coverage_v520(p_tenant_id uuid) returns jsonb language plpgsql stable security definer set search_path=public,private,pg_temp as $$declare total_docs bigint;authoritative bigint;legacy bigint;unclassified bigint;tampered_legacy bigint;begin if not private.gst_v520_has_access(p_tenant_id,'gst_compliance.view') then raise exception 'GST compliance view permission required';end if;select count(*) into total_docs from (select id from public.sales where tenant_id=p_tenant_id and status='posted' union all select id from public.purchases where tenant_id=p_tenant_id and status='posted' union all select id from public.sales_returns where tenant_id=p_tenant_id union all select id from public.purchase_returns where tenant_id=p_tenant_id union all select id from public.purchase_invoices_v484 where tenant_id=p_tenant_id and status not in('draft','void'))z;select count(*) into authoritative from public.gst_document_snapshots_v520 where tenant_id=p_tenant_id;select count(*) into legacy from public.gst_legacy_document_markers_v520 where tenant_id=p_tenant_id;unclassified:=greatest(total_docs-authoritative-legacy,0);select count(*) into tampered_legacy from public.gst_legacy_document_markers_v520 m where m.tenant_id=p_tenant_id and m.source_hash is distinct from(case when private.gst_legacy_source_payload_v520(m.tenant_id,m.source_type,m.source_id) is null then null else encode(extensions.digest(convert_to(private.gst_legacy_source_payload_v520(m.tenant_id,m.source_type,m.source_id)::text,'UTF8'),'sha256'),'hex') end);return jsonb_build_object('total_finalized_documents',total_docs,'authoritative_snapshots',authoritative,'legacy_unverified',legacy,'unclassified_documents',unclassified,'legacy_source_hash_mismatches',tampered_legacy,'ready',unclassified=0 and tampered_legacy=0);end$$;
revoke all on function public.gst_snapshot_coverage_v520(uuid) from public,anon;grant execute on function public.gst_snapshot_coverage_v520(uuid) to authenticated,service_role;
select private.gst_legacy_marker_sync_v520(null);
insert into public.thq_schema_releases(migration_no,schema_version,release_name,notes) values(226,'5.2.0-foundation','Legacy GST Evidence & Coverage','Hashes the original generic-tax header+line facts for pre-v5.2 finalized transactions, marks them legacy_unverified without fabricating GST components, and adds coverage/tamper health checks.') on conflict(migration_no) do update set schema_version=excluded.schema_version,release_name=excluded.release_name,notes=excluded.notes;
commit;