-- THQ ERP v5.2 GST & Compliance - effective-dated GST configuration history
begin;
create table if not exists public.gst_registration_versions_v520 (
 id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade,
 registration_id uuid not null references public.gst_registrations_v520(id) on delete cascade, legal_name text not null, trade_name text,
 registration_type text not null, address_line1 text,address_line2 text,city text,postal_code text,country text not null default 'India',
 einvoice_enabled boolean not null default false, ewaybill_enabled boolean not null default false, returns_enabled boolean not null default true,
 provider_key text, provider_config jsonb not null default '{}'::jsonb, validation_status text not null default 'local_validated', active boolean not null default true,
 effective_from date not null,effective_to date,change_reason text,created_by uuid references auth.users(id),created_at timestamptz not null default now(),
 constraint gst_registration_versions_v520_dates_check check(effective_to is null or effective_to>=effective_from),
 constraint gst_registration_versions_v520_type_check check(registration_type in('regular','composition','casual','sez','isd','tcs','tds','non_resident','other')),
 constraint gst_registration_versions_v520_validation_check check(validation_status in('review_required','local_validated','provider_validated','invalid'))
);
create unique index if not exists ux_gst_registration_versions_v520_current on public.gst_registration_versions_v520(tenant_id,registration_id) where effective_to is null;
create index if not exists idx_gst_registration_versions_v520_period on public.gst_registration_versions_v520(tenant_id,registration_id,effective_from,effective_to);
insert into public.gst_registration_versions_v520(tenant_id,registration_id,legal_name,trade_name,registration_type,address_line1,address_line2,city,postal_code,country,einvoice_enabled,ewaybill_enabled,returns_enabled,provider_key,provider_config,validation_status,active,effective_from,effective_to,change_reason,created_by,created_at)
select r.tenant_id,r.id,r.legal_name,r.trade_name,r.registration_type,r.address_line1,r.address_line2,r.city,r.postal_code,r.country,r.einvoice_enabled,r.ewaybill_enabled,r.returns_enabled,r.provider_key,r.provider_config,r.validation_status,r.active,r.effective_from,r.effective_to,'Backfilled from GST foundation registration',r.created_by,r.created_at
from public.gst_registrations_v520 r where not exists(select 1 from public.gst_registration_versions_v520 v where v.tenant_id=r.tenant_id and v.registration_id=r.id);

create or replace function public.gst_registration_config_v520(p_tenant_id uuid,p_registration_id uuid,p_date date default current_date) returns jsonb language plpgsql stable security definer set search_path=public,private,pg_temp as $$
declare v jsonb;begin
 if not private.gst_v520_has_access(p_tenant_id,'gst_compliance.view') then raise exception 'GST compliance view permission required';end if;
 select to_jsonb(vr)||jsonb_build_object('gstin',r.gstin,'pan',r.pan,'state_code',r.state_code,'registration_id',r.id) into v
 from public.gst_registrations_v520 r join public.gst_registration_versions_v520 vr on vr.tenant_id=r.tenant_id and vr.registration_id=r.id and coalesce(p_date,current_date) between vr.effective_from and coalesce(vr.effective_to,'infinity'::date)
 where r.tenant_id=p_tenant_id and r.id=p_registration_id order by vr.effective_from desc,vr.created_at desc limit 1;return v;end $$;

create or replace function public.gst_registration_save_v520(p_tenant_id uuid,p_id uuid,p_gstin text,p_legal_name text,p_trade_name text,p_registration_type text,p_state_code text,p_address_line1 text,p_address_line2 text,p_city text,p_postal_code text,p_einvoice_enabled boolean,p_ewaybill_enabled boolean,p_returns_enabled boolean,p_provider_key text,p_active boolean,p_effective_from date) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_id uuid:=coalesce(p_id,gen_random_uuid());v_gstin text:=upper(regexp_replace(coalesce(p_gstin,''),'\s','','g'));v_valid jsonb;v_before jsonb;v_type text:=lower(trim(coalesce(p_registration_type,'regular')));v_state text:=trim(coalesce(p_state_code,''));v_date date:=coalesce(p_effective_from,current_date);v_existing public.gst_registrations_v520%rowtype;v_current public.gst_registration_versions_v520%rowtype;
begin
 if not private.gst_v520_has_access(p_tenant_id,'gst_compliance.configure') then raise exception 'GST configuration permission required';end if;
 if nullif(trim(coalesce(p_legal_name,'')),'') is null then raise exception 'GST legal name is required';end if;
 if v_type not in('regular','composition','casual','sez','isd','tcs','tds','non_resident','other') then raise exception 'Invalid GST registration type';end if;
 v_valid:=public.gst_gstin_validate_v520(v_gstin);if not coalesce((v_valid->>'structurally_valid')::boolean,false) then raise exception 'GSTIN failed structural/checksum validation';end if;
 if v_state='' then v_state:=v_valid->>'state_code';end if;if v_state is distinct from(v_valid->>'state_code') then raise exception 'GSTIN state code does not match selected state';end if;
 if not exists(select 1 from public.gst_state_master_v520 where code=v_state and active and not is_special_code) then raise exception 'Invalid active GST state code';end if;
 if p_id is not null then
  select * into v_existing from public.gst_registrations_v520 where id=p_id and tenant_id=p_tenant_id for update;if not found then raise exception 'GST registration not found';end if;v_before:=to_jsonb(v_existing);
  if v_existing.gstin is distinct from v_gstin or v_existing.pan is distinct from(v_valid->>'pan') or v_existing.state_code is distinct from v_state then raise exception 'GSTIN, PAN and state are immutable for a registration. Create a new GST registration instead';end if;
  select * into v_current from public.gst_registration_versions_v520 where tenant_id=p_tenant_id and registration_id=p_id and effective_to is null for update;
  if found and v_date<v_current.effective_from then raise exception 'Effective date cannot precede the current GST configuration version (%)',v_current.effective_from;end if;
 else if exists(select 1 from public.gst_registrations_v520 where tenant_id=p_tenant_id and gstin=v_gstin) then raise exception 'GSTIN already exists for this business';end if;end if;
 if p_id is null then
  insert into public.gst_registrations_v520(id,tenant_id,gstin,pan,legal_name,trade_name,registration_type,state_code,address_line1,address_line2,city,postal_code,einvoice_enabled,ewaybill_enabled,returns_enabled,provider_key,validation_status,active,effective_from,created_by,updated_by)
  values(v_id,p_tenant_id,v_gstin,v_valid->>'pan',trim(p_legal_name),nullif(trim(coalesce(p_trade_name,'')),''),v_type,v_state,nullif(trim(coalesce(p_address_line1,'')),''),nullif(trim(coalesce(p_address_line2,'')),''),nullif(trim(coalesce(p_city,'')),''),nullif(trim(coalesce(p_postal_code,'')),''),coalesce(p_einvoice_enabled,false),coalesce(p_ewaybill_enabled,false),coalesce(p_returns_enabled,true),nullif(trim(coalesce(p_provider_key,'')),''),'local_validated',coalesce(p_active,true),v_date,auth.uid(),auth.uid());
  insert into public.gst_registration_versions_v520(tenant_id,registration_id,legal_name,trade_name,registration_type,address_line1,address_line2,city,postal_code,country,einvoice_enabled,ewaybill_enabled,returns_enabled,provider_key,provider_config,validation_status,active,effective_from,change_reason,created_by)
  values(p_tenant_id,v_id,trim(p_legal_name),nullif(trim(coalesce(p_trade_name,'')),''),v_type,nullif(trim(coalesce(p_address_line1,'')),''),nullif(trim(coalesce(p_address_line2,'')),''),nullif(trim(coalesce(p_city,'')),''),nullif(trim(coalesce(p_postal_code,'')),''),'India',coalesce(p_einvoice_enabled,false),coalesce(p_ewaybill_enabled,false),coalesce(p_returns_enabled,true),nullif(trim(coalesce(p_provider_key,'')),''),'{}'::jsonb,'local_validated',coalesce(p_active,true),v_date,'Initial GST registration configuration',auth.uid());
 else
  if v_current.id is not null and v_date=v_current.effective_from then
   update public.gst_registration_versions_v520 set legal_name=trim(p_legal_name),trade_name=nullif(trim(coalesce(p_trade_name,'')),''),registration_type=v_type,address_line1=nullif(trim(coalesce(p_address_line1,'')),''),address_line2=nullif(trim(coalesce(p_address_line2,'')),''),city=nullif(trim(coalesce(p_city,'')),''),postal_code=nullif(trim(coalesce(p_postal_code,'')),''),einvoice_enabled=coalesce(p_einvoice_enabled,false),ewaybill_enabled=coalesce(p_ewaybill_enabled,false),returns_enabled=coalesce(p_returns_enabled,true),provider_key=nullif(trim(coalesce(p_provider_key,'')),''),validation_status='local_validated',active=coalesce(p_active,true),change_reason='Same-day GST configuration correction' where id=v_current.id;
  else
   if v_current.id is not null then update public.gst_registration_versions_v520 set effective_to=v_date-1 where id=v_current.id;end if;
   insert into public.gst_registration_versions_v520(tenant_id,registration_id,legal_name,trade_name,registration_type,address_line1,address_line2,city,postal_code,country,einvoice_enabled,ewaybill_enabled,returns_enabled,provider_key,provider_config,validation_status,active,effective_from,change_reason,created_by)
   values(p_tenant_id,v_id,trim(p_legal_name),nullif(trim(coalesce(p_trade_name,'')),''),v_type,nullif(trim(coalesce(p_address_line1,'')),''),nullif(trim(coalesce(p_address_line2,'')),''),nullif(trim(coalesce(p_city,'')),''),nullif(trim(coalesce(p_postal_code,'')),''),coalesce(v_existing.country,'India'),coalesce(p_einvoice_enabled,false),coalesce(p_ewaybill_enabled,false),coalesce(p_returns_enabled,true),nullif(trim(coalesce(p_provider_key,'')),''),coalesce(v_existing.provider_config,'{}'::jsonb),'local_validated',coalesce(p_active,true),v_date,'GST registration configuration change',auth.uid());
  end if;
  update public.gst_registrations_v520 set legal_name=trim(p_legal_name),trade_name=nullif(trim(coalesce(p_trade_name,'')),''),registration_type=v_type,address_line1=nullif(trim(coalesce(p_address_line1,'')),''),address_line2=nullif(trim(coalesce(p_address_line2,'')),''),city=nullif(trim(coalesce(p_city,'')),''),postal_code=nullif(trim(coalesce(p_postal_code,'')),''),einvoice_enabled=coalesce(p_einvoice_enabled,false),ewaybill_enabled=coalesce(p_ewaybill_enabled,false),returns_enabled=coalesce(p_returns_enabled,true),provider_key=nullif(trim(coalesce(p_provider_key,'')),''),validation_status='local_validated',active=coalesce(p_active,true),updated_by=auth.uid(),updated_at=now() where id=v_id and tenant_id=p_tenant_id;
 end if;
 perform private.business_audit_write_v471(p_tenant_id,'gst.registration.save','gst_registration',v_id,v_gstin,v_before,(select to_jsonb(r) from public.gst_registrations_v520 r where r.id=v_id));return v_id;
end $$;

create or replace function public.gst_location_registration_set_v520(p_tenant_id uuid,p_location_id uuid,p_registration_id uuid,p_effective_from date default current_date) returns void language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_loc public.business_locations%rowtype;v_reg public.gst_registrations_v520%rowtype;v_current public.gst_location_registrations_v520%rowtype;v_state text;v_date date:=coalesce(p_effective_from,current_date);begin
 if not private.gst_v520_has_access(p_tenant_id,'gst_compliance.configure') then raise exception 'GST configuration permission required';end if;
 select * into v_loc from public.business_locations where id=p_location_id and tenant_id=p_tenant_id and active;if not found then raise exception 'Active location not found';end if;
 select * into v_reg from public.gst_registrations_v520 where id=p_registration_id and tenant_id=p_tenant_id and active;if not found then raise exception 'Active GST registration not found';end if;
 if not exists(select 1 from public.gst_registration_versions_v520 v where v.tenant_id=p_tenant_id and v.registration_id=p_registration_id and v.active and v_date between v.effective_from and coalesce(v.effective_to,'infinity'::date)) then raise exception 'GST registration is not active for the requested effective date';end if;
 v_state:=public.gst_state_code_resolve_v520(v_loc.state);if v_state is not null and v_state is distinct from v_reg.state_code then raise exception 'Location state does not match GST registration state';end if;
 select * into v_current from public.gst_location_registrations_v520 where tenant_id=p_tenant_id and location_id=p_location_id and effective_to is null for update;
 if found then
  if v_date<v_current.effective_from then raise exception 'Effective date cannot precede current location GST mapping (%)',v_current.effective_from;end if;
  if v_current.registration_id=p_registration_id then return;end if;
  if v_date=v_current.effective_from then update public.gst_location_registrations_v520 set registration_id=p_registration_id where id=v_current.id;
  else update public.gst_location_registrations_v520 set effective_to=v_date-1 where id=v_current.id;insert into public.gst_location_registrations_v520(tenant_id,location_id,registration_id,effective_from,created_by) values(p_tenant_id,p_location_id,p_registration_id,v_date,auth.uid());end if;
 else insert into public.gst_location_registrations_v520(tenant_id,location_id,registration_id,effective_from,created_by) values(p_tenant_id,p_location_id,p_registration_id,v_date,auth.uid());end if;
 perform private.business_audit_write_v471(p_tenant_id,'gst.location_registration.set','business_location',p_location_id,v_loc.name,null::jsonb,jsonb_build_object('registration_id',p_registration_id,'gstin',v_reg.gstin,'effective_from',v_date));
end $$;

create or replace function public.gst_party_profile_save_v520(p_tenant_id uuid,p_id uuid,p_party_type text,p_party_id uuid,p_registration_type text,p_gstin text,p_legal_name text,p_trade_name text,p_state_code text,p_place_of_supply_code text,p_address_line1 text,p_address_line2 text,p_city text,p_postal_code text,p_country text,p_active boolean) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$
declare v_id uuid;v_type text:=lower(trim(coalesce(p_party_type,'')));v_regtype text:=lower(trim(coalesce(p_registration_type,'unregistered')));v_gstin text:=nullif(upper(regexp_replace(coalesce(p_gstin,''),'\s','','g')),'');v_valid jsonb;v_state text:=nullif(trim(coalesce(p_state_code,'')),'');v_before jsonb;v_status text;v_date date:=current_date;v_current public.gst_party_registrations_v520%rowtype;begin
 if not private.gst_v520_has_access(p_tenant_id,'gst_compliance.manage') then raise exception 'GST manage permission required';end if;if v_type not in('customer','supplier') then raise exception 'Party type must be customer or supplier';end if;if v_regtype not in('registered','unregistered','composition','sez','export','exempt') then raise exception 'Invalid GST party registration type';end if;
 if v_type='customer' and not exists(select 1 from public.customers where id=p_party_id and tenant_id=p_tenant_id) then raise exception 'Customer not found';end if;if v_type='supplier' and not exists(select 1 from public.suppliers where id=p_party_id and tenant_id=p_tenant_id) then raise exception 'Supplier not found';end if;
 if v_regtype in('registered','composition','sez') then if v_gstin is null then raise exception 'GSTIN is required for this registration type';end if;v_valid:=public.gst_gstin_validate_v520(v_gstin);if not coalesce((v_valid->>'structurally_valid')::boolean,false) then raise exception 'GSTIN failed structural/checksum validation';end if;if v_state is null then v_state:=v_valid->>'state_code';end if;if v_state is distinct from(v_valid->>'state_code') then raise exception 'Party GSTIN state and selected state differ';end if;v_status:='local_validated';else v_gstin:=null;v_status:='not_applicable';end if;
 select * into v_current from public.gst_party_registrations_v520 where tenant_id=p_tenant_id and party_type=v_type and party_id=p_party_id and effective_to is null and is_default for update;
 if p_id is not null and(v_current.id is null or v_current.id<>p_id) then raise exception 'Only the current GST party profile can be changed';end if;if v_current.id is not null then v_before:=to_jsonb(v_current);end if;
 if v_current.id is not null and v_current.effective_from=v_date then
  v_id:=v_current.id;update public.gst_party_registrations_v520 set registration_type=v_regtype,gstin=v_gstin,pan=case when v_gstin is null then null else substring(v_gstin,3,10) end,legal_name=nullif(trim(coalesce(p_legal_name,'')),''),trade_name=nullif(trim(coalesce(p_trade_name,'')),''),state_code=v_state,place_of_supply_code=nullif(trim(coalesce(p_place_of_supply_code,'')),''),address_line1=nullif(trim(coalesce(p_address_line1,'')),''),address_line2=nullif(trim(coalesce(p_address_line2,'')),''),city=nullif(trim(coalesce(p_city,'')),''),postal_code=nullif(trim(coalesce(p_postal_code,'')),''),country=coalesce(nullif(trim(coalesce(p_country,'')),''),'India'),is_default=true,validation_status=v_status,active=coalesce(p_active,true),updated_by=auth.uid(),updated_at=now() where id=v_id;
 else
  if v_current.id is not null then update public.gst_party_registrations_v520 set effective_to=v_date-1,is_default=false,updated_by=auth.uid(),updated_at=now() where id=v_current.id;end if;v_id:=gen_random_uuid();
  insert into public.gst_party_registrations_v520(id,tenant_id,party_type,party_id,registration_type,gstin,pan,legal_name,trade_name,state_code,place_of_supply_code,address_line1,address_line2,city,postal_code,country,is_default,validation_status,active,effective_from,created_by,updated_by)
  values(v_id,p_tenant_id,v_type,p_party_id,v_regtype,v_gstin,case when v_gstin is null then null else substring(v_gstin,3,10) end,nullif(trim(coalesce(p_legal_name,'')),''),nullif(trim(coalesce(p_trade_name,'')),''),v_state,nullif(trim(coalesce(p_place_of_supply_code,'')),''),nullif(trim(coalesce(p_address_line1,'')),''),nullif(trim(coalesce(p_address_line2,'')),''),nullif(trim(coalesce(p_city,'')),''),nullif(trim(coalesce(p_postal_code,'')),''),coalesce(nullif(trim(coalesce(p_country,'')),''),'India'),true,v_status,coalesce(p_active,true),v_date,auth.uid(),auth.uid());
 end if;
 perform private.business_audit_write_v471(p_tenant_id,'gst.party_profile.save','gst_party_registration',v_id,coalesce(v_gstin,p_party_id::text),v_before,(select to_jsonb(g) from public.gst_party_registrations_v520 g where g.id=v_id));return v_id;
end $$;

insert into public.thq_schema_releases(migration_no,schema_version,release_name,notes) values(219,'5.2.0-foundation','GST Configuration History Safety','Effective-dated registration configuration versions, party GST profiles, and location-to-GSTIN assignments; GSTIN/PAN/state identity made immutable per registration.') on conflict(migration_no) do update set schema_version=excluded.schema_version,release_name=excluded.release_name,notes=excluded.notes;
commit;