create table if not exists private.gst_authoritative_tx_context_v520 (txid bigint primary key,tenant_id uuid not null,source_type text not null,source_id uuid null,started_at timestamptz not null default now());
revoke all on private.gst_authoritative_tx_context_v520 from public,anon,authenticated;
grant select,insert,update,delete on private.gst_authoritative_tx_context_v520 to service_role;

drop function if exists private.gst_v520_authoritative_context();
create or replace function private.gst_v520_authoritative_context(p_tenant_id uuid default null,p_source_type text default null) returns boolean language sql stable security definer set search_path=public,private,pg_temp as $$ select exists(select 1 from private.gst_authoritative_tx_context_v520 c where c.txid=txid_current() and (p_tenant_id is null or c.tenant_id=p_tenant_id) and (p_source_type is null or c.source_type=p_source_type)); $$;

create or replace function private.gst_authoritative_context_enter_v520(p_tenant_id uuid,p_source_type text) returns void language plpgsql security definer set search_path=public,private,pg_temp as $$ declare v_txid bigint:=txid_current();v_type text:=lower(trim(coalesce(p_source_type,'')));v_existing private.gst_authoritative_tx_context_v520%rowtype;begin if p_tenant_id is null then raise exception 'GST authoritative tenant is required';end if;if v_type not in('sale','purchase','sales_return','purchase_return','purchase_invoice_v484') then raise exception 'Unsupported GST authoritative source type %',v_type;end if;if not exists(select 1 from public.tenants t where t.id=p_tenant_id and t.status='active') then raise exception 'Active business not found';end if;delete from private.gst_authoritative_tx_context_v520 where started_at<now()-interval '1 day';select * into v_existing from private.gst_authoritative_tx_context_v520 where txid=v_txid;if found then if v_existing.tenant_id<>p_tenant_id or v_existing.source_type<>v_type then raise exception 'GST authoritative context already belongs to another source';end if;return;end if;insert into private.gst_authoritative_tx_context_v520(txid,tenant_id,source_type) values(v_txid,p_tenant_id,v_type);end $$;
create or replace function private.gst_authoritative_context_bind_v520(p_source_id uuid) returns void language plpgsql security definer set search_path=public,private,pg_temp as $$ begin if p_source_id is null then raise exception 'GST authoritative source id is required';end if;update private.gst_authoritative_tx_context_v520 set source_id=p_source_id where txid=txid_current();if not found then raise exception 'GST authoritative context is not active';end if;end $$;
create or replace function private.gst_authoritative_context_exit_v520() returns void language sql security definer set search_path=public,private,pg_temp as $$ delete from private.gst_authoritative_tx_context_v520 where txid=txid_current(); $$;

create or replace function private.gst_mark_legacy_source_v520(p_tenant_id uuid,p_source_type text,p_source_id uuid) returns uuid language plpgsql security definer set search_path=public,private,pg_temp as $$ declare v_payload jsonb;v_id uuid;v_source_number text;v_document_date date;v_location_id uuid;v_taxable numeric;v_tax numeric;v_grand numeric;begin if p_tenant_id is null or p_source_id is null then return null;end if;if private.gst_v520_authoritative_context(p_tenant_id,p_source_type) then return null;end if;if exists(select 1 from public.gst_document_snapshots_v520 s where s.tenant_id=p_tenant_id and s.source_type=p_source_type and s.source_id=p_source_id) then return null;end if;select m.id into v_id from public.gst_legacy_document_markers_v520 m where m.tenant_id=p_tenant_id and m.source_type=p_source_type and m.source_id=p_source_id;if v_id is not null then return v_id;end if;v_payload:=private.gst_legacy_source_payload_v520(p_tenant_id,p_source_type,p_source_id);if v_payload is null then return null;end if;v_source_number:=nullif(v_payload->>'number','');v_document_date:=nullif(v_payload->>'date','')::date;v_location_id:=nullif(v_payload->>'location_id','')::uuid;v_taxable:=coalesce(nullif(v_payload->>'taxable_total','')::numeric,nullif(v_payload->>'subtotal','')::numeric);v_tax:=coalesce(nullif(v_payload->>'tax_total','')::numeric,0);v_grand:=coalesce(nullif(v_payload->>'grand_total','')::numeric,0);if v_source_number is null or v_document_date is null then raise exception 'Legacy GST evidence source identity is incomplete for % %',p_source_type,p_source_id;end if;insert into public.gst_legacy_document_markers_v520(tenant_id,source_type,source_id,source_number,document_date,location_id,legacy_taxable_total,legacy_tax_total,legacy_grand_total,source_hash) values(p_tenant_id,p_source_type,p_source_id,v_source_number,v_document_date,v_location_id,v_taxable,v_tax,v_grand,encode(extensions.digest(convert_to(v_payload::text,'UTF8'),'sha256'),'hex')) on conflict(tenant_id,source_type,source_id) do nothing returning id into v_id;if v_id is null then select m.id into v_id from public.gst_legacy_document_markers_v520 m where m.tenant_id=p_tenant_id and m.source_type=p_source_type and m.source_id=p_source_id;end if;return v_id;end $$;

create or replace function private.v4_origin_after_insert() returns trigger language plpgsql security definer set search_path=public,private,pg_temp as $$ declare v_shift uuid;v_cash numeric;v_ref text;v_method text;begin if not private.gst_v520_authoritative_context(new.tenant_id,new.entity_type) then perform private.v4_accounting_post_document(new.tenant_id,new.entity_type,new.entity_id);end if;if new.device_id is not null then select id into v_shift from public.cashier_shifts where tenant_id=new.tenant_id and device_id=new.device_id and status='open' order by opened_at desc limit 1;end if;if v_shift is not null and new.entity_type='sale' then select coalesce(sum(amount),0),max(s.sale_number) into v_cash,v_ref from public.sale_payments p join public.sales s on s.id=p.sale_id where p.sale_id=new.entity_id and lower(coalesce(p.payment_method,''))='cash';if v_cash>0 and not exists(select 1 from public.cash_drawer_movements where shift_id=v_shift and reference_type='sale' and reference_id=new.entity_id) then insert into public.cash_drawer_movements(tenant_id,shift_id,movement_type,amount,reference_type,reference_id,reference_number,note,created_by) values(new.tenant_id,v_shift,'sale',v_cash,'sale',new.entity_id,v_ref,'Cash sale',new.created_by);end if;elsif v_shift is not null and new.entity_type='expense' then select payment_method,total_amount,expense_number into v_method,v_cash,v_ref from public.expenses where id=new.entity_id and tenant_id=new.tenant_id;if lower(coalesce(v_method,''))='cash' and coalesce(v_cash,0)>0 and not exists(select 1 from public.cash_drawer_movements where shift_id=v_shift and reference_type='expense' and reference_id=new.entity_id) then insert into public.cash_drawer_movements(tenant_id,shift_id,movement_type,amount,reference_type,reference_id,reference_number,note,created_by) values(new.tenant_id,v_shift,'expense',-abs(v_cash),'expense',new.entity_id,v_ref,'Cash expense',new.created_by);end if;end if;return new;end $$;

revoke all on function private.gst_v520_authoritative_context(uuid,text) from public,anon,authenticated;
revoke all on function private.gst_authoritative_context_enter_v520(uuid,text) from public,anon,authenticated;
revoke all on function private.gst_authoritative_context_bind_v520(uuid) from public,anon,authenticated;
revoke all on function private.gst_authoritative_context_exit_v520() from public,anon,authenticated;
revoke all on function private.gst_mark_legacy_source_v520(uuid,text,uuid) from public,anon,authenticated;
grant execute on function private.gst_v520_authoritative_context(uuid,text) to service_role;
grant execute on function private.gst_authoritative_context_enter_v520(uuid,text) to service_role;
grant execute on function private.gst_authoritative_context_bind_v520(uuid) to service_role;
grant execute on function private.gst_authoritative_context_exit_v520() to service_role;
grant execute on function private.gst_mark_legacy_source_v520(uuid,text,uuid) to service_role;
insert into public.thq_schema_releases(migration_no,schema_version,release_name,notes) values(236,'5.2.0-foundation','GST Authoritative Transaction Context','Adds a private transaction-ID/tenant/source scoped authoritative context. Only matching v5.2 atomic work suppresses the legacy generic origin journal and legacy marker; actor sync and cash drawer behavior remain unchanged. Normal v5.1 posting is untouched.') on conflict(migration_no) do update set schema_version=excluded.schema_version,release_name=excluded.release_name,notes=excluded.notes;